import type { AlumniProfile, ChatHistories } from "./types";

import { palette } from "@/lib/theme/palette";

export const COLS = {
  primary: palette.primary,
  success: palette.success,
  warning: palette.warning,
  danger: palette.error,
  info: palette.info,
};

export const ALUMNI_POOL: readonly AlumniProfile[] = [
  {
    id: "a1",
    name: "Aman Verma",
    avatar: "👨‍💻",
    image:
      "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Google",
    role: "Software Engineer III",
    college: "IIT Delhi",
    branch: "Computer Science",
    year: "2022",
    city: "Bangalore",
    country: "India",
    skills: ["Go", "Python", "Kubernetes", "Distributed Systems"],
    availableFor: ["Referral", "Mentorship"],
    achievements: "Built Google Cloud Storage components. 2x Hackathon Judge.",
    col: COLS.primary,
  },
  {
    id: "a2",
    name: "Pooja Hegde",
    avatar: "👩‍💻",
    image:
      "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Microsoft",
    role: "Senior Cloud Solutions Architect",
    college: "IIT Kanpur",
    branch: "Information Technology",
    year: "2021",
    city: "Hyderabad",
    country: "India",
    skills: ["Azure", "Terraform", "C#", "Docker"],
    availableFor: ["Referral", "Career Guidance"],
    achievements: "Leads Azure Cloud migration squads. Microsoft MVP Mentor.",
    col: COLS.success,
  },
  {
    id: "a3",
    name: "Ritesh Agrawal",
    avatar: "👨‍💼",
    image:
      "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=400&h=500",
    company: "TechCorp",
    role: "Lead Backend Developer",
    college: "BITS Pilani",
    branch: "Electronics & Communication",
    year: "2023",
    city: "Pune",
    country: "India",
    skills: ["Node.js", "MongoDB", "Redis", "React"],
    availableFor: ["Mentorship", "Career Guidance"],
    achievements: "Scaled internal gRPC messaging grids by 400% latency cuts.",
    col: COLS.info,
  },
  {
    id: "a4",
    name: "Sneha Nair",
    avatar: "👩‍🔬",
    image:
      "https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Meta",
    role: "AI Research Scientist",
    college: "IIT Bombay",
    branch: "Computer Science",
    year: "2020",
    city: "Menlo Park",
    country: "USA",
    skills: ["PyTorch", "NLP", "Transformers", "Computer Vision"],
    availableFor: ["Referral", "Mentorship"],
    achievements: "Co-authored LLaMA structural compression weights papers.",
    col: COLS.danger,
  },
  {
    id: "a5",
    name: "Kunal Dev",
    avatar: "👨‍💻",
    image:
      "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Netflix",
    role: "Tech Lead - Streaming",
    college: "IIT Roorkee",
    branch: "Computer Science",
    year: "2018",
    city: "Los Gatos",
    country: "USA",
    skills: ["Node.js", "C++", "WebRTC", "Cassandra"],
    availableFor: ["Referral", "Career Guidance"],
    achievements: "Re-architected edge routing pipelines for 4K live streams.",
    col: COLS.primary,
  },
  {
    id: "a6",
    name: "Anjali Sharma",
    avatar: "👩‍🎨",
    image:
      "https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Apple",
    role: "Frontend Architect",
    college: "BITS Pilani",
    branch: "Information Technology",
    year: "2019",
    city: "Cupertino",
    country: "USA",
    skills: ["React", "Swift", "WebGL", "TypeScript"],
    availableFor: ["Mentorship", "Referral"],
    achievements: "Shipped core interactive web elements for Apple Vision Pro site.",
    col: COLS.success,
  },
  {
    id: "a7",
    name: "Rohan Das",
    avatar: "👨‍💻",
    image:
      "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Uber",
    role: "Staff Engineer",
    college: "IIT Delhi",
    branch: "Computer Science",
    year: "2017",
    city: "San Francisco",
    country: "USA",
    skills: ["Go", "Redis", "Kafka", "Docker"],
    availableFor: ["Referral", "Mentorship"],
    achievements: "Designed real-time routing engines matching 10M rides daily.",
    col: COLS.info,
  },
  {
    id: "a8",
    name: "Shreya Ghoshal",
    avatar: "👩‍🔬",
    image:
      "https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Nvidia",
    role: "Senior Deep Learning Dev",
    college: "IIT Bombay",
    branch: "Information Technology",
    year: "2021",
    city: "Santa Clara",
    country: "USA",
    skills: ["CUDA", "PyTorch", "C++", "GPU Kernels"],
    availableFor: ["Referral", "Career Guidance"],
    achievements: "Optimized TensorRT inference throughput bounds by 2.4x.",
    col: COLS.danger,
  },
  {
    id: "a9",
    name: "Vikram Aditya",
    avatar: "👨‍✈️",
    image:
      "https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=400&h=500",
    company: "CrowdStrike",
    role: "Security Researcher",
    college: "IIT Kanpur",
    branch: "Computer Science",
    year: "2022",
    city: "Austin",
    country: "USA",
    skills: ["Rust", "Kernel Dev", "Assembly", "C"],
    availableFor: ["Mentorship", "Career Guidance"],
    achievements: "Patched critical zero-day virtualization bugs inside hypervisors.",
    col: COLS.warning,
  },
  {
    id: "a10",
    name: "Neha Kakkar",
    avatar: "👩‍💻",
    image:
      "https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=400&h=500",
    company: "Adobe",
    role: "Senior Product Engineer",
    college: "BITS Pilani",
    branch: "Computer Science",
    year: "2020",
    city: "Noida",
    country: "India",
    skills: ["WebAssembly", "WebGL", "React", "Rust"],
    availableFor: ["Referral", "Mentorship"],
    achievements:
      "Ported key Creative Cloud drawing canvases to run natively in browser.",
    col: COLS.info,
  },
];

export const INITIAL_CHAT_HISTORIES: ChatHistories = {
  a1: [
    {
      sender: "alumnus",
      text: "Hey Rahul! Let me know if you need referrals for Google. Happy to help.",
      time: "Yesterday",
    },
  ],
  a2: [
    {
      sender: "alumnus",
      text: "Hey! Azure Solutions team is expanding. Let's sync on your credentials next week.",
      time: "3 days ago",
    },
  ],
  a3: [
    {
      sender: "alumnus",
      text: "Hey Rahul! Saw your PathEd Roadmap progression. You did really well on the Distributed Systems challenge. Let me know if you need referrals or resumes checked.",
      time: "Yesterday, 3:10 PM",
    },
  ],
  a6: [
    {
      sender: "alumnus",
      text: "Hi Rahul! Your React and WebGL milestones are impressive. Glad to connect with you.",
      time: "2 days ago",
    },
  ],
};

export const INITIAL_CONNECTED_IDS = ["a3", "a6"];

export const REFERRAL_LOCK_MS = 30 * 24 * 60 * 60 * 1000;
