import type { ChallengeQuestion } from "@/lib/challenges/types";
import { codingProblem } from "@/lib/problems/helpers";

type Spec = Parameters<typeof codingProblem>[1];

function node(val: number, left: unknown = null, right: unknown = null) {
  return { val, left, right };
}

const SPECS: Spec[] = [
  {
    slug: "maximum-depth-binary-tree",
    title: "Maximum Depth of Binary Tree",
    difficulty: "easy",
    xp: 70,
    minutes: 20,
    topics: ["trees", "dfs", "dsa"],
    icon: "tree",
    desc: "Rooted binary tree nodes are {val,left,right}. Return max depth.",
    prompt: "maxDepth(root) → number. null → 0.",
    hints: ["DFS: 1 + max(left, right).", "BFS level count also works.", "Null child is 0."],
    editorial: "Recurse both subtrees; depth is 1 + max child.",
    complexity: "Time O(n), Space O(h)",
    params: "root",
    fn: "maxDepth",
    examples: [{ input: "root = [3,9,20,null,null,15,7]", output: "3" }],
    publicTests: [
      { args: [node(3, node(9), node(20, node(15), node(7)))], expected: 3 },
      { args: [node(1, null, node(2))], expected: 2 },
      { args: [null], expected: 0 },
    ],
    hiddenTests: [
      { args: [node(1)], expected: 1 },
      { args: [node(1, node(2, node(3)))], expected: 3 },
    ],
  },
  {
    slug: "invert-binary-tree",
    title: "Invert Binary Tree",
    difficulty: "easy",
    xp: 70,
    minutes: 20,
    topics: ["trees", "dfs", "dsa"],
    icon: "tree",
    desc: "Swap every left/right child and return the root.",
    prompt: "invertTree(root) → inverted root.",
    hints: ["Swap then recurse (or recurse then swap).", "Null stays null.", "BFS swap also works."],
    editorial: "Post-order swap children.",
    complexity: "Time O(n), Space O(h)",
    params: "root",
    fn: "invertTree",
    examples: [{ input: "root=[2,1,3]", output: "[2,3,1]" }],
    publicTests: [
      { args: [node(2, node(1), node(3))], expected: node(2, node(3), node(1)) },
      { args: [null], expected: null },
    ],
    hiddenTests: [
      { args: [node(1)], expected: node(1) },
      {
        args: [node(4, node(2, node(1), node(3)), node(7, node(6), node(9)))],
        expected: node(4, node(7, node(9), node(6)), node(2, node(3), node(1))),
      },
    ],
  },
  {
    slug: "same-tree",
    title: "Same Tree",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["trees", "dfs", "dsa"],
    icon: "tree",
    desc: "True if two binary trees are structurally identical with same values.",
    prompt: "isSameTree(p, q) → boolean.",
    hints: ["Both null → true.", "One null → false.", "vals equal and recurse."],
    editorial: "Simultaneous DFS.",
    complexity: "Time O(n), Space O(h)",
    params: "p, q",
    fn: "isSameTree",
    examples: [{ input: "p=[1,2,3], q=[1,2,3]", output: "true" }],
    publicTests: [
      { args: [node(1, node(2), node(3)), node(1, node(2), node(3))], expected: true },
      { args: [node(1, node(2)), node(1, null, node(2))], expected: false },
    ],
    hiddenTests: [
      { args: [null, null], expected: true },
      { args: [node(1), node(1, node(2))], expected: false },
    ],
  },
  {
    slug: "path-sum",
    title: "Path Sum",
    difficulty: "easy",
    xp: 75,
    minutes: 20,
    topics: ["trees", "dfs", "dsa"],
    icon: "tree",
    desc: "True if a root-to-leaf path sums to targetSum.",
    prompt: "hasPathSum(root, targetSum) → boolean.",
    hints: ["Subtract node.val as you go.", "Leaf: remaining === 0.", "Null → false."],
    editorial: "DFS remaining sum.",
    complexity: "Time O(n), Space O(h)",
    params: "root, targetSum",
    fn: "hasPathSum",
    examples: [{ input: "root=[5,4,8,...], targetSum=22", output: "true" }],
    publicTests: [
      {
        args: [
          node(5, node(4, node(11, node(7), node(2))), node(8, node(13), node(4, null, node(1)))),
          22,
        ],
        expected: true,
      },
      { args: [node(1, node(2), node(3)), 5], expected: false },
      { args: [null, 0], expected: false },
    ],
    hiddenTests: [
      { args: [node(1, node(2)), 1], expected: false },
      { args: [node(1), 1], expected: true },
    ],
  },
  {
    slug: "symmetric-tree",
    title: "Symmetric Tree",
    difficulty: "easy",
    xp: 80,
    minutes: 20,
    topics: ["trees", "dfs", "dsa"],
    icon: "tree",
    desc: "True if the tree is a mirror of itself.",
    prompt: "isSymmetric(root) → boolean.",
    hints: ["Compare left vs right subtrees.", "Mirror: l.left vs r.right.", "BFS two queues."],
    editorial: "Recursive mirror check.",
    complexity: "Time O(n), Space O(h)",
    params: "root",
    fn: "isSymmetric",
    examples: [{ input: "root=[1,2,2,3,4,4,3]", output: "true" }],
    publicTests: [
      {
        args: [node(1, node(2, node(3), node(4)), node(2, node(4), node(3)))],
        expected: true,
      },
      { args: [node(1, node(2, null, node(3)), node(2, null, node(3)))], expected: false },
    ],
    hiddenTests: [
      { args: [null], expected: true },
      { args: [node(1)], expected: true },
    ],
  },
  {
    slug: "number-of-islands",
    title: "Number of Islands",
    difficulty: "medium",
    xp: 150,
    minutes: 30,
    topics: ["graphs", "dfs", "bfs", "dsa"],
    icon: "globe",
    desc: "Grid of '1' land and '0' water. Count islands.",
    prompt: "numIslands(grid) → count. Mutating the grid is allowed.",
    hints: ["DFS/BFS flood fill.", "Sink visited land to '0'.", "4-directional."],
    editorial: "Flood fill each unvisited land cell.",
    complexity: "Time O(mn), Space O(mn)",
    params: "grid",
    fn: "numIslands",
    examples: [{ input: 'grid=[["1","1","0"],["1","0","0"],["0","0","1"]]', output: "2" }],
    publicTests: [
      {
        args: [
          [
            ["1", "1", "1", "1", "0"],
            ["1", "1", "0", "1", "0"],
            ["1", "1", "0", "0", "0"],
            ["0", "0", "0", "0", "0"],
          ],
        ],
        expected: 1,
      },
      {
        args: [
          [
            ["1", "1", "0", "0", "0"],
            ["1", "1", "0", "0", "0"],
            ["0", "0", "1", "0", "0"],
            ["0", "0", "0", "1", "1"],
          ],
        ],
        expected: 3,
      },
    ],
    hiddenTests: [
      { args: [[["0"]]], expected: 0 },
      { args: [[["1"]]], expected: 1 },
    ],
    weekly: true,
  },
  {
    slug: "flood-fill",
    title: "Flood Fill",
    difficulty: "easy",
    xp: 80,
    minutes: 20,
    topics: ["graphs", "dfs", "dsa"],
    icon: "globe",
    desc: "4-direction flood fill from (sr,sc) with color. Return the image.",
    prompt: "floodFill(image, sr, sc, color) → image.",
    hints: ["If start already color, return.", "DFS neighbors with same original.", "Copy or mutate."],
    editorial: "DFS/BFS from start pixel.",
    complexity: "Time O(mn), Space O(mn)",
    params: "image, sr, sc, color",
    fn: "floodFill",
    examples: [
      { input: "image=[[1,1,1],[1,1,0],[1,0,1]], sr=1, sc=1, color=2", output: "[[2,2,2],[2,2,0],[2,0,1]]" },
    ],
    publicTests: [
      {
        args: [
          [
            [1, 1, 1],
            [1, 1, 0],
            [1, 0, 1],
          ],
          1,
          1,
          2,
        ],
        expected: [
          [2, 2, 2],
          [2, 2, 0],
          [2, 0, 1],
        ],
      },
    ],
    hiddenTests: [
      {
        args: [
          [
            [0, 0, 0],
            [0, 0, 0],
          ],
          0,
          0,
          0,
        ],
        expected: [
          [0, 0, 0],
          [0, 0, 0],
        ],
      },
    ],
  },
  {
    slug: "clone-graph-adj",
    title: "Clone Graph (Adjacency List)",
    difficulty: "medium",
    xp: 160,
    minutes: 35,
    topics: ["graphs", "dfs", "dsa"],
    icon: "network",
    desc: "Nodes 1..n. graph[i] is a list of neighbors of node i+1 (1-indexed). Return the same adjacency list cloned (deep copy as new arrays).",
    prompt: "cloneGraph(graph) → new adjacency list with copied neighbor arrays.",
    hints: ["Copy each neighbor list.", "Do not mutate input.", "Empty graph → []."],
    editorial: "Map old node → new node; copy edges.",
    complexity: "Time O(V+E), Space O(V+E)",
    params: "graph",
    fn: "cloneGraph",
    examples: [{ input: "graph=[[2,4],[1,3],[2,4],[1,3]]", output: "same structure" }],
    publicTests: [
      {
        args: [[[2, 4], [1, 3], [2, 4], [1, 3]]],
        expected: [[2, 4], [1, 3], [2, 4], [1, 3]],
      },
      { args: [[]], expected: [] },
    ],
    hiddenTests: [
      { args: [[[2], [1]]], expected: [[2], [1]] },
      { args: [[[]]], expected: [[]] },
    ],
  },
  {
    slug: "course-schedule",
    title: "Course Schedule",
    difficulty: "medium",
    xp: 160,
    minutes: 35,
    topics: ["graphs", "topo-sort", "dsa"],
    icon: "network",
    desc: "numCourses, prerequisites [a,b] meaning b before a. True if you can finish all.",
    prompt: "canFinish(numCourses, prerequisites) → boolean.",
    hints: ["Cycle in directed graph → false.", "Kahn indegree BFS.", "DFS coloring also works."],
    editorial: "Topological sort; fail on leftover nodes.",
    complexity: "Time O(V+E), Space O(V+E)",
    params: "numCourses, prerequisites",
    fn: "canFinish",
    examples: [
      { input: "numCourses=2, prerequisites=[[1,0]]", output: "true" },
      { input: "numCourses=2, prerequisites=[[1,0],[0,1]]", output: "false" },
    ],
    publicTests: [
      { args: [2, [[1, 0]]], expected: true },
      { args: [2, [[1, 0], [0, 1]]], expected: false },
    ],
    hiddenTests: [
      { args: [1, []], expected: true },
      { args: [3, [[0, 1], [0, 2], [1, 2]]], expected: true },
    ],
    weekly: true,
  },
  {
    slug: "rotting-oranges",
    title: "Rotting Oranges",
    difficulty: "medium",
    xp: 150,
    minutes: 30,
    topics: ["graphs", "bfs", "dsa"],
    icon: "globe",
    desc: "0 empty, 1 fresh, 2 rotten. Minutes until all fresh rot, else -1. 4-dir.",
    prompt: "orangesRotting(grid) → minutes or -1.",
    hints: ["Multi-source BFS from all 2s.", "Count fresh.", "If fresh remain, -1."],
    editorial: "Level BFS from initially rotten cells.",
    complexity: "Time O(mn), Space O(mn)",
    params: "grid",
    fn: "orangesRotting",
    examples: [{ input: "grid=[[2,1,1],[1,1,0],[0,1,1]]", output: "4" }],
    publicTests: [
      {
        args: [
          [
            [2, 1, 1],
            [1, 1, 0],
            [0, 1, 1],
          ],
        ],
        expected: 4,
      },
      {
        args: [
          [
            [2, 1, 1],
            [0, 1, 1],
            [1, 0, 1],
          ],
        ],
        expected: -1,
      },
    ],
    hiddenTests: [
      { args: [[[0, 2]]], expected: 0 },
      { args: [[[1]]], expected: -1 },
    ],
  },
  {
    slug: "kth-largest-element",
    title: "Kth Largest Element",
    difficulty: "medium",
    xp: 120,
    minutes: 25,
    topics: ["heaps", "sorting", "dsa"],
    icon: "bolt",
    desc: "k-th largest element in an unsorted array (1-indexed from largest).",
    prompt: "findKthLargest(nums, k) → value.",
    hints: ["Sort descending and index k-1.", "Quickselect average O(n).", "Min-heap of size k."],
    editorial: "Sort or heap/quickselect.",
    complexity: "Time O(n log n) sort, Space O(1)",
    params: "nums, k",
    fn: "findKthLargest",
    examples: [
      { input: "nums=[3,2,1,5,6,4], k=2", output: "5" },
      { input: "nums=[3,2,3,1,2,4,5,5,6], k=4", output: "4" },
    ],
    publicTests: [
      { args: [[3, 2, 1, 5, 6, 4], 2], expected: 5 },
      { args: [[3, 2, 3, 1, 2, 4, 5, 5, 6], 4], expected: 4 },
    ],
    hiddenTests: [
      { args: [[1], 1], expected: 1 },
      { args: [[7, 6, 5, 4], 1], expected: 7 },
    ],
  },
  {
    slug: "top-k-frequent",
    title: "Top K Frequent Elements",
    difficulty: "medium",
    xp: 130,
    minutes: 25,
    topics: ["heaps", "hashing", "dsa"],
    icon: "bolt",
    desc: "k most frequent numbers. Return them sorted descending by frequency then value.",
    prompt: "topKFrequent(nums, k) → k values, freq desc then value desc.",
    hints: ["Count map.", "Sort entries.", "Tie-break by larger value."],
    editorial: "Count then sort or bucket sort.",
    complexity: "Time O(n log n), Space O(n)",
    params: "nums, k",
    fn: "topKFrequent",
    examples: [{ input: "nums=[1,1,1,2,2,3], k=2", output: "[1,2]" }],
    publicTests: [
      { args: [[1, 1, 1, 2, 2, 3], 2], expected: [1, 2] },
      { args: [[1], 1], expected: [1] },
    ],
    hiddenTests: [
      { args: [[4, 1, -1, 2, -1, 2, 3], 2], expected: [2, -1] },
      { args: [[1, 2], 2], expected: [2, 1] },
    ],
  },
  {
    slug: "merge-intervals",
    title: "Merge Intervals",
    difficulty: "medium",
    xp: 140,
    minutes: 25,
    topics: ["intervals", "sorting", "dsa"],
    desc: "Merge overlapping [start,end] intervals.",
    prompt: "merge(intervals) → merged, sorted by start.",
    hints: ["Sort by start.", "If cur.start <= last.end, extend.", "Else push new."],
    editorial: "Sort + linear merge.",
    complexity: "Time O(n log n), Space O(n)",
    params: "intervals",
    fn: "merge",
    examples: [{ input: "intervals=[[1,3],[2,6],[8,10],[15,18]]", output: "[[1,6],[8,10],[15,18]]" }],
    publicTests: [
      {
        args: [
          [
            [1, 3],
            [2, 6],
            [8, 10],
            [15, 18],
          ],
        ],
        expected: [
          [1, 6],
          [8, 10],
          [15, 18],
        ],
      },
      {
        args: [
          [
            [1, 4],
            [4, 5],
          ],
        ],
        expected: [[1, 5]],
      },
    ],
    hiddenTests: [
      { args: [[[1, 4]]], expected: [[1, 4]] },
      {
        args: [
          [
            [1, 4],
            [0, 4],
          ],
        ],
        expected: [[0, 4]],
      },
    ],
  },
  {
    slug: "insert-interval",
    title: "Insert Interval",
    difficulty: "medium",
    xp: 140,
    minutes: 25,
    topics: ["intervals", "dsa"],
    desc: "Insert newInterval into sorted non-overlapping intervals and merge.",
    prompt: "insert(intervals, newInterval) → result.",
    hints: ["Push all that end before new.start.", "Merge overlaps.", "Append the rest."],
    editorial: "Three-way scan.",
    complexity: "Time O(n), Space O(n)",
    params: "intervals, newInterval",
    fn: "insert",
    examples: [{ input: "intervals=[[1,3],[6,9]], newInterval=[2,5]", output: "[[1,5],[6,9]]" }],
    publicTests: [
      {
        args: [
          [
            [1, 3],
            [6, 9],
          ],
          [2, 5],
        ],
        expected: [
          [1, 5],
          [6, 9],
        ],
      },
    ],
    hiddenTests: [
      { args: [[], [5, 7]], expected: [[5, 7]] },
      {
        args: [
          [
            [1, 5],
          ],
          [2, 3],
        ],
        expected: [[1, 5]],
      },
    ],
  },
  {
    slug: "binary-tree-level-order",
    title: "Binary Tree Level Order Traversal",
    difficulty: "medium",
    xp: 120,
    minutes: 25,
    topics: ["trees", "bfs", "dsa"],
    icon: "tree",
    desc: "Return values grouped by level (BFS).",
    prompt: "levelOrder(root) → number[][]. Empty tree → [].",
    hints: ["Queue BFS.", "Process length of queue per level.", "Skip null children."],
    editorial: "Classic level-order BFS.",
    complexity: "Time O(n), Space O(n)",
    params: "root",
    fn: "levelOrder",
    examples: [{ input: "root=[3,9,20,null,null,15,7]", output: "[[3],[9,20],[15,7]]" }],
    publicTests: [
      {
        args: [node(3, node(9), node(20, node(15), node(7)))],
        expected: [[3], [9, 20], [15, 7]],
      },
      { args: [node(1)], expected: [[1]] },
      { args: [null], expected: [] },
    ],
    hiddenTests: [
      { args: [node(1, node(2, node(3)))], expected: [[1], [2], [3]] },
    ],
  },
  {
    slug: "lowest-common-ancestor-bst",
    title: "Lowest Common Ancestor of a BST",
    difficulty: "medium",
    xp: 130,
    minutes: 25,
    topics: ["trees", "bst", "dsa"],
    icon: "tree",
    desc: "BST nodes p and q given as values. Return the LCA node object.",
    prompt: "lowestCommonAncestor(root, p, q) → LCA node (object with val).",
    hints: ["If both < root, go left.", "Both > root, go right.", "Else root is LCA."],
    editorial: "Walk using BST order.",
    complexity: "Time O(h), Space O(1)",
    params: "root, p, q",
    fn: "lowestCommonAncestor",
    examples: [{ input: "root=[6,2,8,0,4,7,9], p=2, q=8", output: "6" }],
    publicTests: [
      {
        args: [
          node(6, node(2, node(0), node(4, node(3), node(5))), node(8, node(7), node(9))),
          2,
          8,
        ],
        expected: node(6, node(2, node(0), node(4, node(3), node(5))), node(8, node(7), node(9))),
      },
    ],
    hiddenTests: [
      {
        args: [
          node(6, node(2, node(0), node(4)), node(8)),
          2,
          4,
        ],
        expected: node(2, node(0), node(4)),
      },
    ],
  },
  {
    slug: "range-sum-bst",
    title: "Range Sum of BST",
    difficulty: "easy",
    xp: 70,
    minutes: 15,
    topics: ["trees", "bst", "dsa"],
    icon: "tree",
    desc: "Sum of BST values in [low, high] inclusive.",
    prompt: "rangeSumBST(root, low, high) → sum.",
    hints: ["Prune left if root.val < low.", "Prune right if root.val > high.", "Add when inside range."],
    editorial: "DFS with BST pruning.",
    complexity: "Time O(n), Space O(h)",
    params: "root, low, high",
    fn: "rangeSumBST",
    examples: [{ input: "root=[10,5,15,3,7,null,18], low=7, high=15", output: "32" }],
    publicTests: [
      {
        args: [node(10, node(5, node(3), node(7)), node(15, null, node(18))), 7, 15],
        expected: 32,
      },
    ],
    hiddenTests: [
      { args: [node(10), 1, 20], expected: 10 },
      { args: [node(10, node(5), node(15)), 11, 14], expected: 0 },
    ],
  },
  {
    slug: "decode-ways",
    title: "Decode Ways",
    difficulty: "medium",
    xp: 160,
    minutes: 30,
    topics: ["dynamic-programming", "strings", "dsa"],
    desc: "A->1 ... Z->26. Count ways to decode a digit string.",
    prompt: "numDecodings(s) → ways. Leading zero invalid.",
    hints: ["dp[i] from one-digit and two-digit takes.", "Zero cannot start a code.", "10 and 20 are valid; 30 is not."],
    editorial: "1D DP similar to climb stairs with validity checks.",
    complexity: "Time O(n), Space O(1)",
    params: "s",
    fn: "numDecodings",
    examples: [
      { input: 's="12"', output: "2" },
      { input: 's="226"', output: "3" },
    ],
    publicTests: [
      { args: ["12"], expected: 2 },
      { args: ["226"], expected: 3 },
      { args: ["06"], expected: 0 },
    ],
    hiddenTests: [
      { args: ["10"], expected: 1 },
      { args: ["27"], expected: 1 },
    ],
  },
  {
    slug: "partition-equal-subset-sum",
    title: "Partition Equal Subset Sum",
    difficulty: "medium",
    xp: 170,
    minutes: 35,
    topics: ["dynamic-programming", "dsa"],
    desc: "True if the array can split into two subsets with equal sum.",
    prompt: "canPartition(nums) → boolean.",
    hints: ["Need subset summing to total/2.", "Odd total → false.", "0/1 knapsack boolean DP."],
    editorial: "Subset-sum DP to total/2.",
    complexity: "Time O(n*sum), Space O(sum)",
    params: "nums",
    fn: "canPartition",
    examples: [
      { input: "nums=[1,5,11,5]", output: "true" },
      { input: "nums=[1,2,3,5]", output: "false" },
    ],
    publicTests: [
      { args: [[1, 5, 11, 5]], expected: true },
      { args: [[1, 2, 3, 5]], expected: false },
    ],
    hiddenTests: [
      { args: [[1, 2, 3, 6]], expected: true },
      { args: [[1, 1]], expected: true },
    ],
    weekly: true,
  },
  {
    slug: "edit-distance",
    title: "Edit Distance",
    difficulty: "hard",
    xp: 220,
    minutes: 40,
    topics: ["dynamic-programming", "strings", "dsa"],
    desc: "Min insert/delete/replace operations to turn word1 into word2.",
    prompt: "minDistance(word1, word2) → number.",
    hints: ["dp[i][j] on prefixes.", "If chars equal, dp[i-1][j-1].", "Else 1+min(insert,delete,replace)."],
    editorial: "Classic Levenshtein DP.",
    complexity: "Time O(nm), Space O(nm)",
    params: "word1, word2",
    fn: "minDistance",
    examples: [
      { input: 'word1="horse", word2="ros"', output: "3" },
      { input: 'word1="intention", word2="execution"', output: "5" },
    ],
    publicTests: [
      { args: ["horse", "ros"], expected: 3 },
      { args: ["intention", "execution"], expected: 5 },
    ],
    hiddenTests: [
      { args: ["", "a"], expected: 1 },
      { args: ["abc", "abc"], expected: 0 },
    ],
    weekly: true,
  },
  {
    slug: "longest-palindromic-substring",
    title: "Longest Palindromic Substring",
    difficulty: "medium",
    xp: 160,
    minutes: 30,
    topics: ["strings", "dsa"],
    desc: "Longest palindromic substring. If ties, return the leftmost.",
    prompt: "longestPalindrome(s) → substring.",
    hints: ["Expand around centers.", "Odd and even centers.", "Track best start/len."],
    editorial: "2n-1 expansions.",
    complexity: "Time O(n^2), Space O(1)",
    params: "s",
    fn: "longestPalindrome",
    examples: [
      { input: 's="babad"', output: '"bab"' },
      { input: 's="cbbd"', output: '"bb"' },
    ],
    publicTests: [
      { args: ["babad"], expected: "bab" },
      { args: ["cbbd"], expected: "bb" },
    ],
    hiddenTests: [
      { args: ["a"], expected: "a" },
      { args: ["ac"], expected: "a" },
    ],
  },
  {
    slug: "group-anagrams",
    title: "Group Anagrams",
    difficulty: "medium",
    xp: 130,
    minutes: 25,
    topics: ["strings", "hashing", "dsa"],
    desc: "Group strings that are anagrams. Return groups sorted by the sorted-key, each group sorted lexicographically.",
    prompt: "groupAnagrams(strs) → string[][] as specified.",
    hints: ["Key = sorted characters.", "Map key → list.", "Sort groups and lists for a stable judge."],
    editorial: "Hash by canonical sorted string.",
    complexity: "Time O(n k log k), Space O(nk)",
    params: "strs",
    fn: "groupAnagrams",
    examples: [{ input: 'strs=["eat","tea","tan","ate","nat","bat"]', output: 'grouped anagrams' }],
    publicTests: [
      {
        args: [["eat", "tea", "tan", "ate", "nat", "bat"]],
        expected: [
          ["bat"],
          ["ate", "eat", "tea"],
          ["nat", "tan"],
        ],
      },
    ],
    hiddenTests: [
      { args: [[""]], expected: [[""]] },
      { args: [["a"]], expected: [["a"]] },
    ],
  },
  {
    slug: "three-sum",
    title: "3Sum",
    difficulty: "medium",
    xp: 170,
    minutes: 35,
    topics: ["arrays", "two-pointers", "dsa"],
    desc: "Unique triplets that sum to 0, each triplet sorted, overall sorted.",
    prompt: "threeSum(nums) → number[][].",
    hints: ["Sort.", "Fix i, two-pointer the rest.", "Skip duplicates."],
    editorial: "Sorted two-pointer 3-sum.",
    complexity: "Time O(n^2), Space O(1) extra",
    params: "nums",
    fn: "threeSum",
    examples: [{ input: "nums=[-1,0,1,2,-1,-4]", output: "[[-1,-1,2],[-1,0,1]]" }],
    publicTests: [
      {
        args: [[-1, 0, 1, 2, -1, -4]],
        expected: [
          [-1, -1, 2],
          [-1, 0, 1],
        ],
      },
      { args: [[0, 1, 1]], expected: [] },
    ],
    hiddenTests: [
      { args: [[0, 0, 0]], expected: [[0, 0, 0]] },
      { args: [[]], expected: [] },
    ],
    weekly: true,
  },
  {
    slug: "trapping-rain-water",
    title: "Trapping Rain Water",
    difficulty: "hard",
    xp: 220,
    minutes: 40,
    topics: ["arrays", "two-pointers", "dsa"],
    desc: "How much water can elevation bars trap.",
    prompt: "trap(height) → units of water.",
    hints: ["Min of leftMax/rightMax minus height.", "Two pointers with running maxes.", "Stack of indices also works."],
    editorial: "Two-pointer water trapping.",
    complexity: "Time O(n), Space O(1)",
    params: "height",
    fn: "trap",
    examples: [{ input: "height=[0,1,0,2,1,0,1,3,2,1,2,1]", output: "6" }],
    publicTests: [
      { args: [[0, 1, 0, 2, 1, 0, 1, 3, 2, 1, 2, 1]], expected: 6 },
      { args: [[4, 2, 0, 3, 2, 5]], expected: 9 },
    ],
    hiddenTests: [
      { args: [[1, 0, 1]], expected: 1 },
      { args: [[2, 0, 2]], expected: 2 },
    ],
    weekly: true,
  },
  {
    slug: "sliding-window-maximum",
    title: "Sliding Window Maximum",
    difficulty: "hard",
    xp: 220,
    minutes: 40,
    topics: ["arrays", "deque", "dsa"],
    desc: "Maximum of each window of size k.",
    prompt: "maxSlidingWindow(nums, k) → maxima.",
    hints: ["Monotonic decreasing deque of indices.", "Drop out-of-window fronts.", "Drop smaller backs."],
    editorial: "Deque sliding window maxima.",
    complexity: "Time O(n), Space O(k)",
    params: "nums, k",
    fn: "maxSlidingWindow",
    examples: [{ input: "nums=[1,3,-1,-3,5,3,6,7], k=3", output: "[3,3,5,5,6,7]" }],
    publicTests: [
      { args: [[1, 3, -1, -3, 5, 3, 6, 7], 3], expected: [3, 3, 5, 5, 6, 7] },
      { args: [[1], 1], expected: [1] },
    ],
    hiddenTests: [
      { args: [[9, 8, 7, 6], 2], expected: [9, 8, 7] },
      { args: [[1, -1], 1], expected: [1, -1] },
    ],
    weekly: true,
  },
];

export function extraTreesGraphs(offset: number): ChallengeQuestion[] {
  return SPECS.map((spec, i) => codingProblem(offset + i + 1, spec));
}
