import type { ChallengeQuestion } from "@/lib/challenges/types";
import { codingProblem } from "@/lib/problems/helpers";

type Spec = Parameters<typeof codingProblem>[1];

const SPECS: Spec[] = [
  {
    slug: "contains-duplicate",
    title: "Contains Duplicate",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["arrays", "hashing", "dsa"],
    desc: "Return true if any value appears at least twice.",
    prompt: "Implement containsDuplicate(nums): boolean.",
    hints: ["Use a Set.", "If add fails, you have a duplicate.", "O(n) time is expected."],
    editorial: "Insert into a set while scanning; return true on collision.",
    complexity: "Time O(n), Space O(n)",
    params: "nums",
    fn: "containsDuplicate",
    examples: [
      { input: "nums = [1,2,3,1]", output: "true" },
      { input: "nums = [1,2,3,4]", output: "false" },
    ],
    publicTests: [
      { args: [[1, 2, 3, 1]], expected: true },
      { args: [[1, 2, 3, 4]], expected: false },
      { args: [[1]], expected: false },
    ],
    hiddenTests: [
      { args: [[0, 0]], expected: true },
      { args: [[9, 8, 7, 6, 5]], expected: false },
    ],
  },
  {
    slug: "best-time-to-buy-sell-stock",
    title: "Best Time to Buy and Sell Stock",
    difficulty: "easy",
    xp: 80,
    minutes: 20,
    topics: ["arrays", "greedy", "dsa"],
    desc: "Max profit from one buy and one later sell.",
    prompt: "maxProfit(prices) → max profit, or 0.",
    hints: ["Track min price so far.", "Profit = price - min.", "One pass is enough."],
    editorial: "Kadane-style: keep valley, maximize price - valley.",
    complexity: "Time O(n), Space O(1)",
    params: "prices",
    fn: "maxProfit",
    examples: [
      { input: "prices = [7,1,5,3,6,4]", output: "5" },
      { input: "prices = [7,6,4,3,1]", output: "0" },
    ],
    publicTests: [
      { args: [[7, 1, 5, 3, 6, 4]], expected: 5 },
      { args: [[7, 6, 4, 3, 1]], expected: 0 },
      { args: [[2, 4, 1]], expected: 2 },
    ],
    hiddenTests: [
      { args: [[1, 2]], expected: 1 },
      { args: [[3, 3, 3]], expected: 0 },
    ],
  },
  {
    slug: "maximum-subarray",
    title: "Maximum Subarray",
    difficulty: "medium",
    xp: 110,
    minutes: 25,
    topics: ["arrays", "dynamic-programming", "dsa"],
    desc: "Largest sum of any contiguous subarray.",
    prompt: "maxSubArray(nums) → number.",
    hints: ["Kadane: max(ending here, current).", "Reset when ending-here goes negative.", "Handle all-negative arrays."],
    editorial: "Kadane's algorithm: running best ending at i vs global best.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "maxSubArray",
    examples: [
      { input: "nums = [-2,1,-3,4,-1,2,1,-5,4]", output: "6" },
      { input: "nums = [1]", output: "1" },
    ],
    publicTests: [
      { args: [[-2, 1, -3, 4, -1, 2, 1, -5, 4]], expected: 6 },
      { args: [[1]], expected: 1 },
      { args: [[5, 4, -1, 7, 8]], expected: 23 },
    ],
    hiddenTests: [
      { args: [[-1]], expected: -1 },
      { args: [[-2, -1]], expected: -1 },
    ],
  },
  {
    slug: "move-zeroes",
    title: "Move Zeroes",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["arrays", "two-pointers", "dsa"],
    desc: "Move all zeroes to the end, preserving order of others. Return the array.",
    prompt: "moveZeroes(nums) → nums with zeroes packed to the right.",
    hints: ["Write-index for non-zeroes.", "Fill the rest with 0.", "In-place preferred."],
    editorial: "Two pointers: compact non-zeroes then zero-fill.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "moveZeroes",
    examples: [{ input: "nums = [0,1,0,3,12]", output: "[1,3,12,0,0]" }],
    publicTests: [
      { args: [[0, 1, 0, 3, 12]], expected: [1, 3, 12, 0, 0] },
      { args: [[0]], expected: [0] },
      { args: [[1, 2]], expected: [1, 2] },
    ],
    hiddenTests: [
      { args: [[0, 0, 1]], expected: [1, 0, 0] },
      { args: [[4, 0, 0, 0, 5]], expected: [4, 5, 0, 0, 0] },
    ],
  },
  {
    slug: "plus-one",
    title: "Plus One",
    difficulty: "easy",
    xp: 55,
    minutes: 15,
    topics: ["arrays", "math", "dsa"],
    desc: "Digits of a non-negative integer; add one.",
    prompt: "plusOne(digits) → digit array.",
    hints: ["Walk from the end.", "9 becomes 0 and carry.", "If carry remains, unshift 1."],
    editorial: "Ripple carry from the least significant digit.",
    complexity: "Time O(n), Space O(n) worst case",
    params: "digits",
    fn: "plusOne",
    examples: [
      { input: "digits = [1,2,3]", output: "[1,2,4]" },
      { input: "digits = [9]", output: "[1,0]" },
    ],
    publicTests: [
      { args: [[1, 2, 3]], expected: [1, 2, 4] },
      { args: [[9]], expected: [1, 0] },
      { args: [[9, 9]], expected: [1, 0, 0] },
    ],
    hiddenTests: [
      { args: [[0]], expected: [1] },
      { args: [[1, 9, 9]], expected: [2, 0, 0] },
    ],
  },
  {
    slug: "merge-sorted-array",
    title: "Merge Sorted Array",
    difficulty: "easy",
    xp: 70,
    minutes: 20,
    topics: ["arrays", "two-pointers", "dsa"],
    desc: "Merge nums2 (length n) into nums1 (length m+n, extra zeros).",
    prompt: "merge(nums1, m, nums2, n) → merged nums1.",
    hints: ["Fill from the back.", "Compare nums1[m-1] and nums2[n-1].", "Drain leftover nums2."],
    editorial: "Three pointers from the right to avoid overwrite.",
    complexity: "Time O(m+n), Space O(1)",
    params: "nums1, m, nums2, n",
    fn: "merge",
    examples: [
      { input: "nums1=[1,2,3,0,0,0], m=3, nums2=[2,5,6], n=3", output: "[1,2,2,3,5,6]" },
    ],
    publicTests: [
      { args: [[1, 2, 3, 0, 0, 0], 3, [2, 5, 6], 3], expected: [1, 2, 2, 3, 5, 6] },
      { args: [[1], 1, [], 0], expected: [1] },
      { args: [[0], 0, [1], 1], expected: [1] },
    ],
    hiddenTests: [
      { args: [[2, 0], 1, [1], 1], expected: [1, 2] },
      { args: [[4, 5, 6, 0, 0, 0], 3, [1, 2, 3], 3], expected: [1, 2, 3, 4, 5, 6] },
    ],
  },
  {
    slug: "intersection-of-two-arrays",
    title: "Intersection of Two Arrays",
    difficulty: "easy",
    xp: 65,
    minutes: 15,
    topics: ["arrays", "hashing", "dsa"],
    desc: "Unique intersection of two integer arrays (any order).",
    prompt: "intersection(nums1, nums2) → unique common values sorted ascending.",
    hints: ["Put one array in a Set.", "Scan the other.", "Deduplicate the result."],
    editorial: "Set membership; sort the unique result ascending.",
    complexity: "Time O(n+m), Space O(n)",
    params: "nums1, nums2",
    fn: "intersection",
    examples: [{ input: "nums1=[1,2,2,1], nums2=[2,2]", output: "[2]" }],
    publicTests: [
      { args: [[1, 2, 2, 1], [2, 2]], expected: [2] },
      { args: [[4, 9, 5], [9, 4, 9, 8, 4]], expected: [4, 9] },
    ],
    hiddenTests: [
      { args: [[1], [2]], expected: [] },
      { args: [[1, 1], [1]], expected: [1] },
    ],
  },
  {
    slug: "majority-element",
    title: "Majority Element",
    difficulty: "easy",
    xp: 70,
    minutes: 20,
    topics: ["arrays", "hashing", "dsa"],
    desc: "Element that appears more than n/2 times.",
    prompt: "majorityElement(nums) → the majority value.",
    hints: ["Boyer-Moore voting.", "Count cancels minorities.", "Guaranteed to exist."],
    editorial: "Boyer-Moore: candidate + count.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "majorityElement",
    examples: [
      { input: "nums = [3,2,3]", output: "3" },
      { input: "nums = [2,2,1,1,1,2,2]", output: "2" },
    ],
    publicTests: [
      { args: [[3, 2, 3]], expected: 3 },
      { args: [[2, 2, 1, 1, 1, 2, 2]], expected: 2 },
    ],
    hiddenTests: [
      { args: [[1]], expected: 1 },
      { args: [[1, 1, 1, 2, 3]], expected: 1 },
    ],
  },
  {
    slug: "missing-number",
    title: "Missing Number",
    difficulty: "easy",
    xp: 65,
    minutes: 15,
    topics: ["arrays", "math", "bit-manipulation", "dsa"],
    desc: "Array of n distinct numbers in [0, n]; find the missing one.",
    prompt: "missingNumber(nums) → missing value.",
    hints: ["Sum formula n(n+1)/2.", "XOR 0..n with all nums.", "Avoid overflow with XOR."],
    editorial: "Expected sum minus actual, or XOR fold.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "missingNumber",
    examples: [
      { input: "nums = [3,0,1]", output: "2" },
      { input: "nums = [0,1]", output: "2" },
    ],
    publicTests: [
      { args: [[3, 0, 1]], expected: 2 },
      { args: [[0, 1]], expected: 2 },
      { args: [[9, 6, 4, 2, 3, 5, 7, 0, 1]], expected: 8 },
    ],
    hiddenTests: [
      { args: [[0]], expected: 1 },
      { args: [[1]], expected: 0 },
    ],
  },
  {
    slug: "single-number",
    title: "Single Number",
    difficulty: "easy",
    xp: 70,
    minutes: 15,
    topics: ["bit-manipulation", "arrays", "dsa"],
    desc: "Every element appears twice except one.",
    prompt: "singleNumber(nums) → the unique value.",
    hints: ["XOR is its own inverse.", "a^a=0, a^0=a.", "Fold XOR across the array."],
    editorial: "XOR all values; pairs cancel.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "singleNumber",
    examples: [
      { input: "nums = [2,2,1]", output: "1" },
      { input: "nums = [4,1,2,1,2]", output: "4" },
    ],
    publicTests: [
      { args: [[2, 2, 1]], expected: 1 },
      { args: [[4, 1, 2, 1, 2]], expected: 4 },
      { args: [[1]], expected: 1 },
    ],
    hiddenTests: [
      { args: [[0, 1, 0]], expected: 1 },
      { args: [[7, 3, 7]], expected: 3 },
    ],
  },
  {
    slug: "product-of-array-except-self",
    title: "Product of Array Except Self",
    difficulty: "medium",
    xp: 140,
    minutes: 30,
    topics: ["arrays", "prefix", "dsa"],
    desc: "For each index, product of all other elements. No division.",
    prompt: "productExceptSelf(nums) → products array.",
    hints: ["Prefix products left-to-right.", "Then multiply suffix from the right.", "O(1) extra besides output."],
    editorial: "Two-pass prefix/suffix products.",
    complexity: "Time O(n), Space O(1) extra",
    params: "nums",
    fn: "productExceptSelf",
    examples: [{ input: "nums = [1,2,3,4]", output: "[24,12,8,6]" }],
    publicTests: [
      { args: [[1, 2, 3, 4]], expected: [24, 12, 8, 6] },
      { args: [[-1, 1, 0, -3, 3]], expected: [0, 0, 9, 0, 0] },
    ],
    hiddenTests: [
      { args: [[2, 3]], expected: [3, 2] },
      { args: [[1, 1, 1, 1]], expected: [1, 1, 1, 1] },
    ],
    weekly: true,
  },
  {
    slug: "container-with-most-water",
    title: "Container With Most Water",
    difficulty: "medium",
    xp: 130,
    minutes: 25,
    topics: ["arrays", "two-pointers", "dsa"],
    desc: "Two lines form a container; maximize area.",
    prompt: "maxArea(height) → max water.",
    hints: ["Start at both ends.", "Move the shorter pointer.", "Area = min(h[l],h[r]) * (r-l)."],
    editorial: "Two pointers: the shorter wall is the bottleneck.",
    complexity: "Time O(n), Space O(1)",
    params: "height",
    fn: "maxArea",
    examples: [{ input: "height = [1,8,6,2,5,4,8,3,7]", output: "49" }],
    publicTests: [
      { args: [[1, 8, 6, 2, 5, 4, 8, 3, 7]], expected: 49 },
      { args: [[1, 1]], expected: 1 },
    ],
    hiddenTests: [
      { args: [[4, 3, 2, 1, 4]], expected: 16 },
      { args: [[1, 2, 1]], expected: 2 },
    ],
  },
  {
    slug: "valid-anagram",
    title: "Valid Anagram",
    difficulty: "easy",
    xp: 55,
    minutes: 15,
    topics: ["strings", "hashing", "dsa"],
    desc: "True if t is an anagram of s.",
    prompt: "isAnagram(s, t) → boolean.",
    hints: ["Same length first.", "Count characters.", "26-slot array if lowercase."],
    editorial: "Frequency maps must match.",
    complexity: "Time O(n), Space O(1) alphabet",
    params: "s, t",
    fn: "isAnagram",
    examples: [
      { input: 's="anagram", t="nagaram"', output: "true" },
      { input: 's="rat", t="car"', output: "false" },
    ],
    publicTests: [
      { args: ["anagram", "nagaram"], expected: true },
      { args: ["rat", "car"], expected: false },
    ],
    hiddenTests: [
      { args: ["a", "a"], expected: true },
      { args: ["ab", "a"], expected: false },
    ],
  },
  {
    slug: "valid-palindrome",
    title: "Valid Palindrome",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["strings", "two-pointers", "dsa"],
    desc: "Alphanumeric palindrome, ignoring case.",
    prompt: "isPalindrome(s) → boolean.",
    hints: ["Skip non-alphanumeric.", "Compare lowercase.", "Two pointers inward."],
    editorial: "Filter or skip in-place with two pointers.",
    complexity: "Time O(n), Space O(1)",
    params: "s",
    fn: "isPalindrome",
    examples: [
      { input: 's="A man, a plan, a canal: Panama"', output: "true" },
      { input: 's="race a car"', output: "false" },
    ],
    publicTests: [
      { args: ["A man, a plan, a canal: Panama"], expected: true },
      { args: ["race a car"], expected: false },
      { args: [" "], expected: true },
    ],
    hiddenTests: [
      { args: ["0P"], expected: false },
      { args: ["ab_a"], expected: true },
    ],
  },
  {
    slug: "reverse-string",
    title: "Reverse String",
    difficulty: "easy",
    xp: 45,
    minutes: 10,
    topics: ["strings", "two-pointers", "dsa"],
    desc: "Reverse an array of characters in place and return it.",
    prompt: "reverseString(s) → reversed char array.",
    hints: ["Swap i and n-1-i.", "Stop at midpoint.", "Return the same array."],
    editorial: "Two-pointer swap.",
    complexity: "Time O(n), Space O(1)",
    params: "s",
    fn: "reverseString",
    examples: [{ input: 's=["h","e","l","l","o"]', output: '["o","l","l","e","h"]' }],
    publicTests: [
      { args: [["h", "e", "l", "l", "o"]], expected: ["o", "l", "l", "e", "h"] },
      { args: [["H", "a"]], expected: ["a", "H"] },
    ],
    hiddenTests: [
      { args: [["a"]], expected: ["a"] },
      { args: [["1", "2", "3", "4"]], expected: ["4", "3", "2", "1"] },
    ],
  },
  {
    slug: "first-unique-character",
    title: "First Unique Character",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["strings", "hashing", "dsa"],
    desc: "Index of first non-repeating character, or -1.",
    prompt: "firstUniqChar(s) → index.",
    hints: ["Count frequencies.", "Second pass for count==1.", "Lowercase assumed."],
    editorial: "Two-pass frequency table.",
    complexity: "Time O(n), Space O(1)",
    params: "s",
    fn: "firstUniqChar",
    examples: [
      { input: 's="leetcode"', output: "0" },
      { input: 's="aabb"', output: "-1" },
    ],
    publicTests: [
      { args: ["leetcode"], expected: 0 },
      { args: ["loveleetcode"], expected: 2 },
      { args: ["aabb"], expected: -1 },
    ],
    hiddenTests: [
      { args: ["z"], expected: 0 },
      { args: ["aadadaad"], expected: -1 },
    ],
  },
  {
    slug: "longest-common-prefix",
    title: "Longest Common Prefix",
    difficulty: "easy",
    xp: 65,
    minutes: 15,
    topics: ["strings", "dsa"],
    desc: "Longest shared prefix of an array of strings.",
    prompt: "longestCommonPrefix(strs) → prefix string.",
    hints: ["Start with strs[0].", "Shrink while others disagree.", "Empty array → \"\"."],
    editorial: "Vertical scan or prefix shrink.",
    complexity: "Time O(S), Space O(1)",
    params: "strs",
    fn: "longestCommonPrefix",
    examples: [
      { input: 'strs=["flower","flow","flight"]', output: '"fl"' },
      { input: 'strs=["dog","racecar","car"]', output: '""' },
    ],
    publicTests: [
      { args: [["flower", "flow", "flight"]], expected: "fl" },
      { args: [["dog", "racecar", "car"]], expected: "" },
    ],
    hiddenTests: [
      { args: [["a"]], expected: "a" },
      { args: [["interspecies", "interstellar", "interstate"]], expected: "inters" },
    ],
  },
  {
    slug: "implement-strstr",
    title: "Find the Index of the First Occurrence",
    difficulty: "easy",
    xp: 70,
    minutes: 20,
    topics: ["strings", "dsa"],
    desc: "Index of needle in haystack, or -1.",
    prompt: "strStr(haystack, needle) → index.",
    hints: ["Empty needle → 0.", "Slide a window of needle.length.", "KMP optional."],
    editorial: "Naive window compare is fine at this size.",
    complexity: "Time O(n*m), Space O(1)",
    params: "haystack, needle",
    fn: "strStr",
    examples: [
      { input: 'haystack="sadbutsad", needle="sad"', output: "0" },
      { input: 'haystack="leetcode", needle="leeto"', output: "-1" },
    ],
    publicTests: [
      { args: ["sadbutsad", "sad"], expected: 0 },
      { args: ["leetcode", "leeto"], expected: -1 },
      { args: ["hello", "ll"], expected: 2 },
    ],
    hiddenTests: [
      { args: ["a", "a"], expected: 0 },
      { args: ["abc", ""], expected: 0 },
    ],
  },
  {
    slug: "valid-parentheses",
    title: "Valid Parentheses",
    difficulty: "easy",
    xp: 75,
    minutes: 20,
    topics: ["strings", "stack", "dsa"],
    desc: "Every open bracket is closed in the correct order.",
    prompt: "isValid(s) → boolean for ()[]{}.",
    hints: ["Push opens.", "Pop on close and match.", "Stack empty at end."],
    editorial: "Classic stack matching.",
    complexity: "Time O(n), Space O(n)",
    params: "s",
    fn: "isValid",
    examples: [
      { input: 's="()"', output: "true" },
      { input: 's="(]"', output: "false" },
    ],
    publicTests: [
      { args: ["()"], expected: true },
      { args: ["()[]{}"], expected: true },
      { args: ["(]"], expected: false },
    ],
    hiddenTests: [
      { args: ["{[]}"], expected: true },
      { args: ["]"], expected: false },
    ],
  },
  {
    slug: "is-subsequence",
    title: "Is Subsequence",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["strings", "two-pointers", "dsa"],
    desc: "True if s is a subsequence of t.",
    prompt: "isSubsequence(s, t) → boolean.",
    hints: ["Two pointers.", "Advance s only on match.", "s exhausted → true."],
    editorial: "Greedy scan of t.",
    complexity: "Time O(|t|), Space O(1)",
    params: "s, t",
    fn: "isSubsequence",
    examples: [
      { input: 's="abc", t="ahbgdc"', output: "true" },
      { input: 's="axc", t="ahbgdc"', output: "false" },
    ],
    publicTests: [
      { args: ["abc", "ahbgdc"], expected: true },
      { args: ["axc", "ahbgdc"], expected: false },
    ],
    hiddenTests: [
      { args: ["", "ahbgdc"], expected: true },
      { args: ["b", "abc"], expected: true },
    ],
  },
  {
    slug: "length-of-last-word",
    title: "Length of Last Word",
    difficulty: "easy",
    xp: 45,
    minutes: 10,
    topics: ["strings", "dsa"],
    desc: "Length of the last word in a space-separated string.",
    prompt: "lengthOfLastWord(s) → number.",
    hints: ["Trim trailing spaces.", "Count backward until space.", "Words are non-space runs."],
    editorial: "Scan from the right.",
    complexity: "Time O(n), Space O(1)",
    params: "s",
    fn: "lengthOfLastWord",
    examples: [
      { input: 's="Hello World"', output: "5" },
      { input: 's="   fly me   to   the moon  "', output: "4" },
    ],
    publicTests: [
      { args: ["Hello World"], expected: 5 },
      { args: ["   fly me   to   the moon  "], expected: 4 },
    ],
    hiddenTests: [
      { args: ["a"], expected: 1 },
      { args: ["day"], expected: 3 },
    ],
  },
  {
    slug: "roman-to-integer",
    title: "Roman to Integer",
    difficulty: "easy",
    xp: 70,
    minutes: 20,
    topics: ["strings", "hashing", "dsa"],
    desc: "Convert a Roman numeral to an integer.",
    prompt: "romanToInt(s) → number.",
    hints: ["Map I,V,X,L,C,D,M.", "If cur < next, subtract.", "Else add."],
    editorial: "Lookahead subtractive notation.",
    complexity: "Time O(n), Space O(1)",
    params: "s",
    fn: "romanToInt",
    examples: [
      { input: 's="III"', output: "3" },
      { input: 's="MCMXCIV"', output: "1994" },
    ],
    publicTests: [
      { args: ["III"], expected: 3 },
      { args: ["LVIII"], expected: 58 },
      { args: ["MCMXCIV"], expected: 1994 },
    ],
    hiddenTests: [
      { args: ["IX"], expected: 9 },
      { args: ["XL"], expected: 40 },
    ],
  },
  {
    slug: "add-binary",
    title: "Add Binary",
    difficulty: "easy",
    xp: 75,
    minutes: 20,
    topics: ["strings", "math", "dsa"],
    desc: "Sum two binary strings; return binary.",
    prompt: "addBinary(a, b) → binary string.",
    hints: ["Walk from the end.", "Carry 0/1.", "Prepend remaining carry."],
    editorial: "Schoolbook addition on bits.",
    complexity: "Time O(max(n,m)), Space O(n)",
    params: "a, b",
    fn: "addBinary",
    examples: [
      { input: 'a="11", b="1"', output: '"100"' },
      { input: 'a="1010", b="1011"', output: '"10101"' },
    ],
    publicTests: [
      { args: ["11", "1"], expected: "100" },
      { args: ["1010", "1011"], expected: "10101" },
    ],
    hiddenTests: [
      { args: ["0", "0"], expected: "0" },
      { args: ["1", "1"], expected: "10" },
    ],
  },
  {
    slug: "house-robber",
    title: "House Robber",
    difficulty: "medium",
    xp: 120,
    minutes: 25,
    topics: ["dynamic-programming", "arrays", "dsa"],
    desc: "Max money without robbing adjacent houses.",
    prompt: "rob(nums) → max amount.",
    hints: ["dp[i] = max(dp[i-1], dp[i-2]+nums[i]).", "Two rolling vars.", "Empty → 0."],
    editorial: "Standard 1D DP with two states.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "rob",
    examples: [
      { input: "nums = [1,2,3,1]", output: "4" },
      { input: "nums = [2,7,9,3,1]", output: "12" },
    ],
    publicTests: [
      { args: [[1, 2, 3, 1]], expected: 4 },
      { args: [[2, 7, 9, 3, 1]], expected: 12 },
      { args: [[2, 1, 1, 2]], expected: 4 },
    ],
    hiddenTests: [
      { args: [[1]], expected: 1 },
      { args: [[0, 0, 0]], expected: 0 },
    ],
  },
  {
    slug: "min-cost-climbing-stairs",
    title: "Min Cost Climbing Stairs",
    difficulty: "easy",
    xp: 80,
    minutes: 20,
    topics: ["dynamic-programming", "dsa"],
    desc: "Pay cost[i] to step on i; can start at 0 or 1. Reach the top.",
    prompt: "minCostClimbingStairs(cost) → min cost.",
    hints: ["dp[i] = cost[i] + min(dp[i-1], dp[i-2]).", "Answer is min of last two.", "Start from the end."],
    editorial: "Fibonacci-like min cost.",
    complexity: "Time O(n), Space O(1)",
    params: "cost",
    fn: "minCostClimbingStairs",
    examples: [
      { input: "cost = [10,15,20]", output: "15" },
      { input: "cost = [1,100,1,1,1,100,1,1,100,1]", output: "6" },
    ],
    publicTests: [
      { args: [[10, 15, 20]], expected: 15 },
      { args: [[1, 100, 1, 1, 1, 100, 1, 1, 100, 1]], expected: 6 },
    ],
    hiddenTests: [
      { args: [[0, 0, 0, 0]], expected: 0 },
      { args: [[1, 0]], expected: 0 },
    ],
  },
  {
    slug: "unique-paths",
    title: "Unique Paths",
    difficulty: "medium",
    xp: 120,
    minutes: 25,
    topics: ["dynamic-programming", "math", "dsa"],
    desc: "Robot from (0,0) to (m-1,n-1) moving right/down. Count paths.",
    prompt: "uniquePaths(m, n) → path count.",
    hints: ["dp[i][j] = dp[i-1][j] + dp[i][j-1].", "First row/col = 1.", "Combinatorics C(m+n-2, m-1)."],
    editorial: "Grid DP or binomial coefficient.",
    complexity: "Time O(mn), Space O(n)",
    params: "m, n",
    fn: "uniquePaths",
    examples: [
      { input: "m=3, n=7", output: "28" },
      { input: "m=3, n=2", output: "3" },
    ],
    publicTests: [
      { args: [3, 7], expected: 28 },
      { args: [3, 2], expected: 3 },
      { args: [1, 1], expected: 1 },
    ],
    hiddenTests: [
      { args: [2, 3], expected: 3 },
      { args: [7, 3], expected: 28 },
    ],
  },
  {
    slug: "coin-change",
    title: "Coin Change",
    difficulty: "medium",
    xp: 150,
    minutes: 30,
    topics: ["dynamic-programming", "dsa"],
    desc: "Fewest coins to make amount. -1 if impossible.",
    prompt: "coinChange(coins, amount) → min coins.",
    hints: ["dp[x] = min over coin of dp[x-coin]+1.", "Init dp[0]=0, rest Inf.", "Unbounded knapsack."],
    editorial: "Unbounded knapsack DP.",
    complexity: "Time O(amount * coins), Space O(amount)",
    params: "coins, amount",
    fn: "coinChange",
    examples: [
      { input: "coins=[1,2,5], amount=11", output: "3" },
      { input: "coins=[2], amount=3", output: "-1" },
    ],
    publicTests: [
      { args: [[1, 2, 5], 11], expected: 3 },
      { args: [[2], 3], expected: -1 },
      { args: [[1], 0], expected: 0 },
    ],
    hiddenTests: [
      { args: [[1, 2, 5], 0], expected: 0 },
      { args: [[2, 5, 10, 1], 27], expected: 4 },
    ],
    weekly: true,
  },
  {
    slug: "jump-game",
    title: "Jump Game",
    difficulty: "medium",
    xp: 130,
    minutes: 25,
    topics: ["greedy", "arrays", "dsa"],
    desc: "From index 0, nums[i] is max jump length. Can you reach the last index?",
    prompt: "canJump(nums) → boolean.",
    hints: ["Track farthest reachable.", "If i > farthest, fail.", "Success if farthest >= last."],
    editorial: "Greedy reachability.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "canJump",
    examples: [
      { input: "nums=[2,3,1,1,4]", output: "true" },
      { input: "nums=[3,2,1,0,4]", output: "false" },
    ],
    publicTests: [
      { args: [[2, 3, 1, 1, 4]], expected: true },
      { args: [[3, 2, 1, 0, 4]], expected: false },
    ],
    hiddenTests: [
      { args: [[0]], expected: true },
      { args: [[2, 0, 0]], expected: true },
    ],
  },
  {
    slug: "longest-increasing-subsequence",
    title: "Longest Increasing Subsequence",
    difficulty: "medium",
    xp: 160,
    minutes: 35,
    topics: ["dynamic-programming", "arrays", "dsa"],
    desc: "Length of the longest strictly increasing subsequence.",
    prompt: "lengthOfLIS(nums) → length.",
    hints: ["dp[i] = 1 + max dp[j] for j<i nums[j]<nums[i].", "Patience sorting / tails binary search.", "O(n log n) optional."],
    editorial: "O(n^2) DP is acceptable; tails array is O(n log n).",
    complexity: "Time O(n^2) or O(n log n)",
    params: "nums",
    fn: "lengthOfLIS",
    examples: [
      { input: "nums=[10,9,2,5,3,7,101,18]", output: "4" },
      { input: "nums=[0,1,0,3,2,3]", output: "4" },
    ],
    publicTests: [
      { args: [[10, 9, 2, 5, 3, 7, 101, 18]], expected: 4 },
      { args: [[0, 1, 0, 3, 2, 3]], expected: 4 },
      { args: [[7, 7, 7, 7]], expected: 1 },
    ],
    hiddenTests: [
      { args: [[1, 2, 3]], expected: 3 },
      { args: [[4, 3, 2, 1]], expected: 1 },
    ],
    weekly: true,
  },
  {
    slug: "word-break",
    title: "Word Break",
    difficulty: "medium",
    xp: 150,
    minutes: 30,
    topics: ["dynamic-programming", "strings", "dsa"],
    desc: "True if s can be segmented into dictionary words.",
    prompt: "wordBreak(s, wordDict) → boolean.",
    hints: ["dp[i] true if prefix s[0..i) segments.", "Try each word ending at i.", "Set for O(1) lookup."],
    editorial: "Boolean DP over prefixes.",
    complexity: "Time O(n^2), Space O(n)",
    params: "s, wordDict",
    fn: "wordBreak",
    examples: [
      { input: 's="leetcode", wordDict=["leet","code"]', output: "true" },
      { input: 's="catsandog", wordDict=["cats","dog","sand","and","cat"]', output: "false" },
    ],
    publicTests: [
      { args: ["leetcode", ["leet", "code"]], expected: true },
      { args: ["applepenapple", ["apple", "pen"]], expected: true },
      { args: ["catsandog", ["cats", "dog", "sand", "and", "cat"]], expected: false },
    ],
    hiddenTests: [
      { args: ["a", ["a"]], expected: true },
      { args: ["aaaaaaa", ["aaaa", "aaa"]], expected: true },
    ],
  },
  {
    slug: "fibonacci-number",
    title: "Fibonacci Number",
    difficulty: "easy",
    xp: 45,
    minutes: 10,
    topics: ["dynamic-programming", "math", "dsa"],
    desc: "Return F(n) with F(0)=0, F(1)=1.",
    prompt: "fib(n) → F(n).",
    hints: ["Iterative two vars.", "Avoid exponential recursion.", "n up to 30 is fine either way."],
    editorial: "Bottom-up Fibonacci.",
    complexity: "Time O(n), Space O(1)",
    params: "n",
    fn: "fib",
    examples: [
      { input: "n=2", output: "1" },
      { input: "n=4", output: "3" },
    ],
    publicTests: [
      { args: [2], expected: 1 },
      { args: [3], expected: 2 },
      { args: [4], expected: 3 },
    ],
    hiddenTests: [
      { args: [0], expected: 0 },
      { args: [10], expected: 55 },
    ],
  },
  {
    slug: "running-sum",
    title: "Running Sum of 1D Array",
    difficulty: "easy",
    xp: 45,
    minutes: 10,
    topics: ["arrays", "prefix", "dsa"],
    desc: "Return prefix sums of nums.",
    prompt: "runningSum(nums) → prefix array.",
    hints: ["Accumulate in place or new array.", "out[i] = out[i-1] + nums[i]."],
    editorial: "Prefix sums.",
    complexity: "Time O(n), Space O(n)",
    params: "nums",
    fn: "runningSum",
    examples: [{ input: "nums=[1,2,3,4]", output: "[1,3,6,10]" }],
    publicTests: [
      { args: [[1, 2, 3, 4]], expected: [1, 3, 6, 10] },
      { args: [[1, 1, 1, 1, 1]], expected: [1, 2, 3, 4, 5] },
    ],
    hiddenTests: [
      { args: [[3]], expected: [3] },
      { args: [[0, 0, 1]], expected: [0, 0, 1] },
    ],
  },
  {
    slug: "pivot-index",
    title: "Find Pivot Index",
    difficulty: "easy",
    xp: 70,
    minutes: 15,
    topics: ["arrays", "prefix", "dsa"],
    desc: "Index where left sum equals right sum, or -1. Leftmost.",
    prompt: "pivotIndex(nums) → index.",
    hints: ["Total sum.", "Walk leftSum.", "right = total - left - nums[i]."],
    editorial: "One pass after total.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "pivotIndex",
    examples: [{ input: "nums=[1,7,3,6,5,6]", output: "3" }],
    publicTests: [
      { args: [[1, 7, 3, 6, 5, 6]], expected: 3 },
      { args: [[1, 2, 3]], expected: -1 },
      { args: [[2, 1, -1]], expected: 0 },
    ],
    hiddenTests: [
      { args: [[0, 0]], expected: 0 },
      { args: [[1]], expected: 0 },
    ],
  },
  {
    slug: "remove-duplicates-sorted",
    title: "Remove Duplicates from Sorted Array",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["arrays", "two-pointers", "dsa"],
    desc: "In-place unique prefix of a sorted array. Return the unique count. The first k elements must be the unique values in order.",
    prompt: "removeDuplicates(nums) → k (unique length). Mutate nums prefix.",
    hints: ["Slow pointer for writes.", "Skip equals.", "Return slow."],
    editorial: "Two-pointer unique compact.",
    complexity: "Time O(n), Space O(1)",
    params: "nums",
    fn: "removeDuplicates",
    examples: [{ input: "nums=[1,1,2]", output: "2" }],
    publicTests: [
      { args: [[1, 1, 2]], expected: 2 },
      { args: [[0, 0, 1, 1, 1, 2, 2, 3, 3, 4]], expected: 5 },
    ],
    hiddenTests: [
      { args: [[1]], expected: 1 },
      { args: [[1, 2, 3]], expected: 3 },
    ],
  },
  {
    slug: "search-insert-position",
    title: "Search Insert Position",
    difficulty: "easy",
    xp: 60,
    minutes: 15,
    topics: ["arrays", "binary-search", "dsa"],
    desc: "Index of target in sorted distinct nums, or insert index.",
    prompt: "searchInsert(nums, target) → index.",
    hints: ["Binary search lower bound.", "If all smaller, return n."],
    editorial: "Lower-bound binary search.",
    complexity: "Time O(log n), Space O(1)",
    params: "nums, target",
    fn: "searchInsert",
    examples: [{ input: "nums=[1,3,5,6], target=5", output: "2" }],
    publicTests: [
      { args: [[1, 3, 5, 6], 5], expected: 2 },
      { args: [[1, 3, 5, 6], 2], expected: 1 },
      { args: [[1, 3, 5, 6], 7], expected: 4 },
    ],
    hiddenTests: [
      { args: [[1, 3, 5, 6], 0], expected: 0 },
      { args: [[1], 1], expected: 0 },
    ],
  },
  {
    slug: "happy-number",
    title: "Happy Number",
    difficulty: "easy",
    xp: 70,
    minutes: 15,
    topics: ["hashing", "math", "dsa"],
    desc: "Replace n by sum of squares of digits until 1 (happy) or a cycle.",
    prompt: "isHappy(n) → boolean.",
    hints: ["Set of seen.", "Cycle if repeat.", "Floyd cycle optional."],
    editorial: "Detect cycle in digit-square sequence.",
    complexity: "Time O(log n), Space O(log n)",
    params: "n",
    fn: "isHappy",
    examples: [
      { input: "n=19", output: "true" },
      { input: "n=2", output: "false" },
    ],
    publicTests: [
      { args: [19], expected: true },
      { args: [2], expected: false },
    ],
    hiddenTests: [
      { args: [1], expected: true },
      { args: [7], expected: true },
    ],
  },
];

export function extraCoding(offset: number): ChallengeQuestion[] {
  return SPECS.map((spec, i) => codingProblem(offset + i + 1, spec));
}
