import type { ChallengeMcqItem, ChallengeQuestion } from "@/lib/challenges/types";
import { DEFAULT_DESIGN_DIMS, designProblem, mcqProblem, projectProblem } from "@/lib/problems/helpers";
import type { ProjectAssessmentSpec } from "@/lib/projects/types";

function q(
  id: number,
  prompt: string,
  opts: string[],
  correct: number,
  explanation: string,
): ChallengeMcqItem {
  return { id, q: prompt, opts, correct, explanation };
}

const MCQ_PACK: Array<Parameters<typeof mcqProblem>[1]> = [
  {
    slug: "time-complexity-quiz",
    title: "Time Complexity Fundamentals",
    difficulty: "easy",
    xp: 80,
    minutes: 8,
    topics: ["algorithms", "complexity", "dsa"],
    desc: "Big-O of common operations and loops.",
    hints: ["Drop constants.", "Nested loops multiply.", "Binary search is log n."],
    editorial: "Count dominant operations; ignore lower-order terms.",
    questions: [
      q(1, "Binary search on a sorted array is:", ["O(n)", "O(log n)", "O(n log n)", "O(1)"], 1, "Halves the search space each step."),
      q(2, "Two nested loops over n are typically:", ["O(n)", "O(n^2)", "O(log n)", "O(2^n)"], 1, "n * n iterations."),
      q(3, "Hash map average get is:", ["O(n)", "O(log n)", "O(1)", "O(n^2)"], 2, "Average constant with a good hash."),
      q(4, "Mergesort time is:", ["O(n)", "O(n log n)", "O(n^2)", "O(log n)"], 1, "Divide and merge."),
    ],
  },
  {
    slug: "os-process-threads-quiz",
    title: "Processes, Threads, and Scheduling",
    difficulty: "medium",
    xp: 100,
    minutes: 8,
    topics: ["os", "concurrency"],
    desc: "OS process model, threads, and CPU scheduling.",
    hints: ["Threads share address space.", "Context switch cost.", "Preemption."],
    editorial: "Threads share heap/code; processes isolate memory.",
    questions: [
      q(1, "Threads in one process share:", ["PID only", "Address space / heap", "Nothing", "Disk only"], 1, "Same virtual memory."),
      q(2, "A context switch saves/restores:", ["Only the disk cache", "CPU registers and PC", "The entire filesystem", "DNS"], 1, "Scheduler restores register state."),
      q(3, "Preemptive scheduling can:", ["Never interrupt a process", "Interrupt a running process", "Disable the MMU", "Skip syscalls"], 1, "Timer interrupt."),
      q(4, "User-level threads blocking on I/O typically:", ["Block the whole process", "Never block", "Bypass the kernel", "Pin a core"], 0, "The process is scheduled as one."),
    ],
  },
  {
    slug: "dbms-normalization-quiz",
    title: "DBMS Normalization",
    difficulty: "medium",
    xp: 100,
    minutes: 8,
    topics: ["databases", "sql", "dbms"],
    desc: "1NF/2NF/3NF and keys.",
    hints: ["1NF atomic values.", "2NF no partial key deps.", "3NF no transitive deps."],
    editorial: "Normal forms reduce redundancy and update anomalies.",
    questions: [
      q(1, "1NF requires:", ["All keys hashed", "Atomic column values", "No joins", "Only ints"], 1, "No repeating groups."),
      q(2, "2NF is about:", ["Partial dependency on a composite key", "Disk RAID", "Indexes only", "JSON"], 0, "Non-key attrs depend on whole key."),
      q(3, "3NF forbids:", ["Foreign keys", "Transitive dependency of non-key on key", "NULLs", "Views"], 1, "A → B → C among non-keys."),
      q(4, "A candidate key is:", ["Any indexed column", "A minimal unique identifier", "Always a UUID", "A view name"], 1, "Minimal superkey."),
    ],
  },
  {
    slug: "sql-joins-quiz",
    title: "SQL Joins",
    difficulty: "easy",
    xp: 80,
    minutes: 7,
    topics: ["sql", "databases"],
    desc: "INNER, LEFT, CROSS, and filtering.",
    hints: ["INNER keeps matches.", "LEFT keeps left unmatched.", "ON vs WHERE."],
    editorial: "Join type decides which unmatched rows survive.",
    questions: [
      q(1, "INNER JOIN returns:", ["All left rows", "Matching rows only", "Cartesian product always", "Only NULLs"], 1, "On the join predicate."),
      q(2, "LEFT JOIN extra rows have:", ["Right side NULL", "Left side NULL", "Duplicates dropped", "No keys"], 0, "Unmatched left kept."),
      q(3, "CROSS JOIN is:", ["A filtered inner join", "Cartesian product", "A window", "An index"], 1, "Every pair."),
      q(4, "WHERE after LEFT JOIN can:", ["Turn it into an inner join if it filters NULLs", "Never change cardinality", "Create a PK", "Disable indexes"], 0, "Filtering NULL right cols drops unmatched."),
    ],
  },
  {
    slug: "http-rest-quiz",
    title: "HTTP and REST",
    difficulty: "easy",
    xp: 80,
    minutes: 7,
    topics: ["networking", "web", "http"],
    desc: "Methods, status codes, and idempotency.",
    hints: ["GET safe/idempotent.", "PUT vs POST.", "429 rate limit."],
    editorial: "REST uses nouns + HTTP verbs; status codes communicate outcomes.",
    questions: [
      q(1, "Which is safe and idempotent?", ["POST", "GET", "PATCH", "CONNECT"], 1, "GET should not change state."),
      q(2, "Creating a resource typically returns:", ["200 only", "201 Created", "301", "418"], 1, "New resource."),
      q(3, "PUT is typically:", ["Never idempotent", "Idempotent replace", "Only for deletes", "A query"], 1, "Same request twice → same resource."),
      q(4, "429 means:", ["OK", "Too Many Requests", "Not Found", "Conflict"], 1, "Rate limited."),
    ],
  },
  {
    slug: "javascript-event-loop-quiz",
    title: "JavaScript Event Loop",
    difficulty: "medium",
    xp: 100,
    minutes: 8,
    topics: ["javascript", "frontend"],
    desc: "Call stack, microtasks, and macrotasks.",
    hints: ["Promises before timeouts.", "One stack.", "async/await is promises."],
    editorial: "Microtasks (Promises) flush before the next macrotask (setTimeout).",
    questions: [
      q(1, "setTimeout(fn, 0) runs:", ["Before any Promise.then", "As a macrotask after the current stack", "Synchronously", "In WASM"], 1, "Timers are macrotasks."),
      q(2, "Promise.then callbacks are:", ["Microtasks", "OS threads", "GPU", "CSS"], 0, "Microtask queue."),
      q(3, "async function returns:", ["undefined always", "a Promise", "a thread", "a socket"], 1, "Always a promise."),
      q(4, "Blocking the stack with a while(true) will:", ["Still run timers", "Freeze rendering and timers", "Use extra cores automatically", "Skip GC forever only"], 1, "Single-threaded JS."),
    ],
  },
  {
    slug: "react-hooks-quiz",
    title: "React Hooks Essentials",
    difficulty: "medium",
    xp: 100,
    minutes: 8,
    topics: ["react", "frontend", "javascript"],
    desc: "useState, useEffect, and dependency arrays.",
    hints: ["Effects after paint.", "Stale closures.", "Keys on lists."],
    editorial: "Hooks rules + deps determine freshness of effects.",
    questions: [
      q(1, "useEffect with [] runs:", ["Every render", "Once after mount", "Never", "On unmount only"], 1, "Empty deps."),
      q(2, "Missing deps often causes:", ["Stale closures", "Faster renders", "SSR only", "CSS bugs"], 0, "Captured old state."),
      q(3, "Keys help React:", ["Hash CSS", "Reconcile list identity", "Call APIs", "Set cookies"], 1, "Stable identity."),
      q(4, "useState updater function is preferred when:", ["Next state depends on previous", "Never", "Using Redux", "CSS-in-JS"], 0, "Avoid stale state."),
    ],
  },
  {
    slug: "cap-theorem-quiz",
    title: "CAP Theorem",
    difficulty: "medium",
    xp: 110,
    minutes: 8,
    topics: ["system-design", "distributed-systems"],
    desc: "Consistency, availability, partition tolerance.",
    hints: ["Partitions happen.", "CP vs AP.", "Latency is not the C in CAP."],
    editorial: "During a partition you choose C or A; P is not optional on networks.",
    questions: [
      q(1, "CAP C means:", ["CPU", "Linearizability / consistent reads of latest write (informally)", "Cache hit", "Cost"], 1, "Single copy illusion."),
      q(2, "Network partitions are:", ["Impossible in AWS", "A given on real networks", "Solved by RAID", "Only DNS"], 1, "P is required."),
      q(3, "Dynamo-style stores often choose:", ["CA", "AP", "No replication", "Only CPU"], 1, "Availability + partition tolerance."),
      q(4, "A CP system during partition may:", ["Reject some requests", "Never fail", "Drop TCP", "Skip auth"], 0, "Preserve consistency."),
    ],
  },
  {
    slug: "caching-strategies-quiz",
    title: "Caching Strategies",
    difficulty: "medium",
    xp: 100,
    minutes: 8,
    topics: ["system-design", "caching"],
    desc: "TTL, write-through, write-back, stampede.",
    hints: ["Write-through vs write-back.", "TTL vs explicit invalidation.", "Dogpile."],
    editorial: "Pick cache policy from staleness vs write cost.",
    questions: [
      q(1, "Write-through means:", ["Write cache then DB (or both on write path)", "Write DB only", "Never write", "CDN only"], 0, "Cache stays consistent on writes."),
      q(2, "Cache stampede is:", ["Many clients refetch a hot expired key", "A RAID failure", "TLS", "GC"], 0, "Thundering herd."),
      q(3, "TTL is:", ["A lock", "Time-to-live expiration", "A join type", "A JVM flag"], 1, "Soft expiry."),
      q(4, "Write-back risk is:", ["Data loss on crash before flush", "Too consistent", "No reads", "DNS"], 0, "Dirty cache."),
    ],
  },
  {
    slug: "git-workflow-quiz",
    title: "Git Workflow",
    difficulty: "easy",
    xp: 70,
    minutes: 6,
    topics: ["git", "tools"],
    desc: "Commits, rebase vs merge, and detached HEAD.",
    hints: ["Rebase rewrites.", "merge commit.", "force-push danger."],
    editorial: "History rewriting vs explicit merge nodes.",
    questions: [
      q(1, "git rebase typically:", ["Creates a merge commit always", "Replays commits on another base", "Deletes remotes", "Formats code"], 1, "Linearize."),
      q(2, "Detached HEAD means:", ["Repo deleted", "HEAD points at a commit, not a branch", "No index", "SSH fail"], 1, "Nameless checkout."),
      q(3, "force-push to shared main is:", ["Always fine", "Dangerous rewrite of public history", "Required daily", "A rebase undo"], 1, "Rewrites others' history."),
      q(4, "A fast-forward merge:", ["Moves the branch pointer with no extra merge commit", "Always conflicts", "Uses stash", "Tags only"], 0, "When target is ancestor."),
    ],
  },
  {
    slug: "tcp-udp-quiz",
    title: "TCP vs UDP",
    difficulty: "easy",
    xp: 80,
    minutes: 7,
    topics: ["networking", "os"],
    desc: "Reliability, ordering, and use cases.",
    hints: ["TCP handshake.", "UDP for latency.", "Ports on both."],
    editorial: "TCP trades latency for reliability; UDP does the opposite.",
    questions: [
      q(1, "TCP provides:", ["No checksums", "Reliable ordered byte stream", "Only broadcast", "Fixed 64B packets"], 1, "ACK + retransmit."),
      q(2, "UDP is preferred for:", ["Bank ledgers", "Latency-sensitive media / games", "Disk RAID", "TLS 1.0 only"], 1, "Loss tolerated."),
      q(3, "Three-way handshake is:", ["UDP", "TCP", "ARP only", "BGP"], 1, "SYN SYN-ACK ACK."),
      q(4, "Both TCP and UDP use:", ["IP addresses only", "Port numbers", "HTTP verbs", "JSON"], 1, "L4 multiplexing."),
    ],
  },
  {
    slug: "index-selectivity-quiz",
    title: "Database Indexes",
    difficulty: "medium",
    xp: 100,
    minutes: 8,
    topics: ["databases", "sql"],
    desc: "B+ trees, covering indexes, and when indexes hurt writes.",
    hints: ["B+ leaf linked list.", "Write amplification.", "Cardinality."],
    editorial: "Indexes speed reads and slow writes; pick columns with useful selectivity.",
    questions: [
      q(1, "B+ tree leaves are:", ["Unlinked", "Linked for range scans", "Hash only", "JSON"], 1, "Range queries."),
      q(2, "Low-selectivity columns (boolean) as sole indexes are often:", ["Perfect", "Poor; filters little", "Illegal", "WAL"], 1, "Most rows match."),
      q(3, "Each extra index typically:", ["Speeds inserts", "Slows inserts/updates", "Deletes the table", "Disables PK"], 1, "Maintain more structures."),
      q(4, "A covering index:", ["Needs a table heap lookup always", "Satisfies the query from the index alone", "Is a view", "Is RAID"], 1, "Index-only scan."),
    ],
  },
  {
    slug: "authn-authz-quiz",
    title: "AuthN vs AuthZ",
    difficulty: "easy",
    xp: 80,
    minutes: 7,
    topics: ["security", "web"],
    desc: "Authentication, authorization, and tokens.",
    hints: ["Who vs what.", "JWT claims.", "Refresh tokens."],
    editorial: "AuthN identifies; AuthZ permits.",
    questions: [
      q(1, "Authentication answers:", ["What can you do?", "Who are you?", "Where is the data?", "How much QPS?"], 1, "Identity."),
      q(2, "Authorization answers:", ["Who are you?", "What are you allowed to do?", "TLS version?", "Disk type?"], 1, "Permissions."),
      q(3, "A refresh token is typically:", ["Sent on every image request", "Long-lived, used to mint new access tokens", "A CSRF cookie only", "A DB index"], 1, "Rotation pattern."),
      q(4, "Putting secrets in a public JWT payload is:", ["Fine always", "Unsafe; payload is readable", "Impossible", "Required"], 1, "Base64, not encryption."),
    ],
  },
  {
    slug: "python-memory-quiz",
    title: "Python Lists and Complexity",
    difficulty: "easy",
    xp: 70,
    minutes: 6,
    topics: ["python", "dsa"],
    desc: "List vs dict operations in CPython.",
    hints: ["Append amortized O(1).", "Insert front O(n).", "dict average O(1)."],
    editorial: "CPython list is a dynamic array; dict is a hash table.",
    questions: [
      q(1, "list.append average is:", ["O(n)", "O(1) amortized", "O(n log n)", "O(n^2)"], 1, "Over-allocate."),
      q(2, "list.insert(0, x) is:", ["O(1)", "O(n)", "O(log n)", "O(1) amortized"], 1, "Shift elements."),
      q(3, "dict membership average is:", ["O(n)", "O(1)", "O(n log n)", "O(n^2)"], 1, "Hash table."),
      q(4, "Using a list as a queue with pop(0) is:", ["Ideal", "O(n) and usually the wrong tool", "O(1)", "Illegal"], 1, "Use deque."),
    ],
  },
  {
    slug: "load-balancing-quiz",
    title: "Load Balancing",
    difficulty: "medium",
    xp: 100,
    minutes: 8,
    topics: ["system-design", "networking"],
    desc: "L4 vs L7, sticky sessions, health checks.",
    hints: ["L7 can route on path.", "Health checks.", "Least-conn vs RR."],
    editorial: "Pick L4 for raw TCP, L7 for HTTP-aware routing.",
    questions: [
      q(1, "L7 load balancers can route on:", ["IP/port only", "HTTP path and headers", "Disk UUID", "BGP communities only"], 1, "Application data."),
      q(2, "Sticky sessions are risky because:", ["They improve cache hit always", "They couple a client to one instance", "They disable TLS", "They remove health checks"], 1, "Uneven load / failover pain."),
      q(3, "Least-connections is useful when:", ["All requests are identical and tiny", "Request cost varies", "There is one replica", "DNS is off"], 1, "Long vs short work."),
      q(4, "Health checks exist to:", ["Pretty dashboards only", "Stop sending traffic to dead instances", "Increase TTL", "Shard disks"], 1, "Remove bad backends."),
    ],
  },
];

function design(
  slug: string,
  title: string,
  desc: string,
  prompt: string,
  api: string,
  extraReq: string[],
  companies: string[],
  weekly = true,
  monthly = false,
  difficulty: "medium" | "hard" = "hard",
): Parameters<typeof designProblem>[1] {
  return {
    slug,
    title,
    difficulty,
    xp: difficulty === "hard" ? 280 : 200,
    minutes: difficulty === "hard" ? 90 : 60,
    topics: ["system-design", "distributed-systems"],
    companies,
    desc,
    prompt,
    hints: [
      "Start with requirements and scale numbers.",
      "Draw the request path for the hottest API.",
      "Call out one consistency vs availability trade-off.",
    ],
    editorial:
      "Clarify functional/non-functional needs, estimate QPS/storage, sketch APIs and data, then scale with cache, queues, and partitions. State what you would drop first under incident.",
    weekly,
    monthly,
    design: {
      passScore: 70,
      requirements: extraReq,
      nonFunctional: [
        "Availability target (e.g. 99.9%)",
        "p99 latency budget",
        "Durability / consistency model",
      ],
      apiSketch: api,
      dimensions: DEFAULT_DESIGN_DIMS,
    },
  };
}

const DESIGNS: Array<Parameters<typeof designProblem>[1]> = [
  design(
    "design-url-shortener",
    "Design a URL Shortener",
    "TinyURL-style service: create short links, redirect, analytics.",
    "Design APIs, encoding, storage, and redirects at 10k QPS write / 100k QPS read.",
    "POST /v1/links {url,ttl} → {code}\nGET /{code} → 302",
    ["Custom aliases", "Optional expiry", "Basic click counts"],
    ["Amazon", "Google", "ByteDance"],
  ),
  design(
    "design-rate-limiter",
    "Design a Rate Limiter",
    "Gateway rate limiter for public APIs (per key, per IP).",
    "Support token bucket and sliding window. Multi-instance. Fail open vs closed.",
    "Middleware: allow(key) → {allowed, remaining, resetAt}",
    ["Per-API quotas", "Burst vs sustained", "Admin override"],
    ["Stripe", "Cloudflare", "Twilio"],
  ),
  design(
    "design-news-feed",
    "Design a News Feed",
    "Twitter/X-like home timeline: post, follow, fan-out.",
    "Design write path, fan-out-on-write vs on-read, ranking hooks, and pagination.",
    "POST /posts\nGET /feed?cursor=\nPOST /follow/{id}",
    ["Follow graph", "Chronological + ranked", "Mute/block"],
    ["Meta", "X", "LinkedIn"],
  ),
  design(
    "design-chat-system",
    "Design a Chat System",
    "1:1 and group chat with online presence and delivery receipts.",
    "WebSocket/long-poll, message store, fan-out to devices, ordering per conversation.",
    "WS /gateway\nPOST /conversations/:id/messages\nGET /conversations/:id/messages?cursor=",
    ["Read receipts", "Unread counts", "Group of 100"],
    ["WhatsApp", "Slack", "Discord"],
  ),
  design(
    "design-notification-system",
    "Design a Notification System",
    "Email/push/SMS fan-out with templates, retries, and preferences.",
    "Ingest events, template, route by channel, backoff, and preference center.",
    "POST /events\nPUT /users/:id/preferences\nGET /admin/dlq",
    ["At-least-once with idempotency keys", "Quiet hours", "Dead-letter"],
    ["Amazon", "Firebase", "Twilio"],
  ),
  design(
    "design-search-autocomplete",
    "Design Search Autocomplete",
    "Typeahead for a large catalog (products or queries).",
    "Prefix index (trie / ngram), ranking, cache, and freshness from query logs.",
    "GET /suggest?q=&limit=",
    ["Personalization optional", "Typo tolerance light", "Abuse / flood"],
    ["Amazon", "Google", "Shopify"],
  ),
  design(
    "design-parking-lot",
    "Design a Parking Lot System",
    "Multi-level lot: spots by vehicle type, tickets, pricing.",
    "In-memory + DB design, allocation strategy, and concurrent entry/exit.",
    "POST /entry {vehicle}\nPOST /exit {ticketId}",
    ["Motorcycle/car/bus sizes", "Hourly billing", "Display free spots"],
    ["Uber", "Lyft"],
    true,
    false,
    "medium",
  ),
  design(
    "design-file-storage",
    "Design a File Storage Service",
    "Dropbox-like upload, download, sharing, and sync metadata.",
    "Chunked upload, object store, metadata DB, sharing ACLs, conflict sync.",
    "POST /files/upload-session\nGET /files/:id\nPOST /files/:id/share",
    ["Dedup optional", "Version history", "Link sharing"],
    ["Dropbox", "Google", "Box"],
    true,
    true,
  ),
  design(
    "design-video-streaming",
    "Design a Video Streaming Platform",
    "YouTube-like upload, transcode, CDN playback.",
    "Ingest, adaptive bitrate, CDN, metadata, and comments at scale.",
    "POST /videos\nGET /videos/:id/manifest\nGET /watch/:id",
    ["HLS/DASH", "Thumbnails", "Copyright scan hook"],
    ["YouTube", "Netflix", "Twitch"],
    true,
    true,
  ),
  design(
    "design-ride-sharing",
    "Design a Ride Sharing Dispatch",
    "Match riders to nearby drivers with ETA and pricing.",
    "Location stream, matching, surge, and trip state machine.",
    "POST /trips\nGET /drivers/nearby\nPOST /trips/:id/accept",
    ["Geo index", "Cancellations", "Payments handoff"],
    ["Uber", "Lyft", "Ola"],
  ),
  design(
    "design-metrics-pipeline",
    "Design a Metrics / Observability Pipeline",
    "Ingest high-cardinality metrics, query dashboards, alert.",
    "Agents → queue → TSDB, downsampling, and alert manager.",
    "POST /v1/metrics\nGET /query?q=\nPOST /alerts",
    ["Cardinality explosion", "Retention tiers", "Alert routing"],
    ["Datadog", "Grafana", "Amazon"],
  ),
  design(
    "design-e-commerce-checkout",
    "Design E-commerce Checkout",
    "Cart, inventory reservation, payment, and order.",
    "Idempotent payments, stock holds, outbox, and failure compensation.",
    "POST /cart/items\nPOST /checkout\nPOST /payments/webhooks",
    ["Exactly-once payment attempt semantics", "Coupon rules", "Refunds"],
    ["Amazon", "Shopify", "Stripe"],
    true,
    true,
  ),
];

function miniProject(
  slug: string,
  title: string,
  desc: string,
  goal: string,
  stack: string[],
  keywords: string[],
): Parameters<typeof projectProblem>[1] {
  const spec: ProjectAssessmentSpec = {
    type: "project",
    passScore: 70,
    timeLimitMinutes: 120,
    overview: {
      goal,
      stack,
      deliverables: ["Working repo", "README", "Short reflection"],
      estimatedHours: 4,
    },
    steps: [
      {
        id: "scaffold",
        title: "Scaffold",
        instructions: "Create the repo, README, and runnable entrypoint.",
        acceptance: ["Repo exists", "README with run steps"],
        requiredEvidence: ["repo_url"],
      },
      {
        id: "core",
        title: "Core behavior",
        instructions: goal,
        acceptance: ["Happy path works", "One failure case handled"],
        requiredEvidence: ["notes"],
      },
      {
        id: "ship",
        title: "Ship",
        instructions: "Document trade-offs and push.",
        acceptance: ["Reflection", "Shareable repo"],
        requiredEvidence: ["repo_url", "notes"],
      },
    ],
    rubric: [
      { id: "checklist", label: "Steps complete", weight: 30, check: "checklist_complete" },
      { id: "evidence", label: "Evidence present", weight: 25, check: "evidence_present" },
      {
        id: "reflection",
        label: "Reflection keywords",
        weight: 20,
        check: "keyword_notes",
        keywords,
      },
      { id: "gh_readme", label: "README", weight: 15, check: "github_readme" },
      {
        id: "gh_structure",
        label: "Repo structure",
        weight: 10,
        check: "github_structure",
        requiredPaths: ["readme"],
      },
    ],
  };
  return {
    slug,
    title,
    difficulty: "medium",
    xp: 220,
    minutes: 120,
    topics: ["projects", ...stack.map((s) => s.toLowerCase())],
    desc,
    prompt: goal,
    hints: ["Ship a thin vertical slice first.", "Log failures.", "Write the README as if onboarding a teammate."],
    editorial: "A small production-shaped slice with tests or scripts beats a large unfinished design.",
    monthly: true,
    project: spec,
  };
}

const PROJECTS: Array<Parameters<typeof projectProblem>[1]> = [
  miniProject(
    "build-json-kv-store",
    "Build a JSON KV Store CLI",
    "File-backed key-value store with get/set/delete and atomic writes.",
    "Implement a CLI KV store with atomic JSON persistence.",
    ["Python", "JSON", "CLI"],
    ["atomic", "json", "cli", "key"],
  ),
  miniProject(
    "build-markdown-notes-api",
    "Build a Markdown Notes API",
    "REST API for notes with tags and full-text search on title.",
    "CRUD notes with tag filter and title search.",
    ["HTTP", "JSON", "SQLite or JSON file"],
    ["rest", "notes", "tag", "search"],
  ),
  miniProject(
    "build-job-queue-worker",
    "Build a Job Queue Worker",
    "In-process queue with retries, backoff, and dead-letter.",
    "Process jobs with retry/backoff and a DLQ list.",
    ["TypeScript or Python", "Queues"],
    ["retry", "backoff", "queue", "dead"],
  ),
  miniProject(
    "build-rate-limited-proxy",
    "Build a Rate-Limited HTTP Proxy",
    "Tiny reverse proxy that rate-limits by API key header.",
    "Forward HTTP with per-key rate limits and 429s.",
    ["HTTP", "Node or Python"],
    ["proxy", "rate", "limit", "429"],
  ),
];

export function extraMcq(offset: number): ChallengeQuestion[] {
  return MCQ_PACK.map((spec, i) => mcqProblem(offset + i + 1, spec));
}

export function extraDesign(offset: number): ChallengeQuestion[] {
  return DESIGNS.map((spec, i) => designProblem(offset + i + 1, spec));
}

export function extraProjects(offset: number): ChallengeQuestion[] {
  return PROJECTS.map((spec, i) => projectProblem(offset + i + 1, spec));
}
