import type {
  Opportunity,
  OpportunityCategoryMeta,
} from "@/components/opportunities/types";

/**
 * Events & summits catalogue — 36 opportunities across 6 categories.
 *
 * Static content, not a fixture: this is the catalogue the events page renders
 * until a CMS/partner feed replaces it. Kept as a typed `const` so a malformed
 * entry (unknown category, missing cover image) fails typecheck rather than
 * rendering a broken card.
 */
export const EVENT_OPPORTUNITIES: readonly Opportunity[] = [
  // ── Hackathons & competitions ──────────────────────────────────────────────
  {
    id: "o1",
    category: "hackathons",
    title: "Google AI Global Hackathon 2026",
    organizer: "Google Developer Group",
    mode: "Online",
    deadline: "2026-08-15",
    prizePool: "$150,000",
    difficulty: "Advanced",
    eligibility: "Students & Professionals",
    tech: "Vertex AI, Gemini API, Flutter",
    seatsLeft: 84,
    parthed_og: true,
    desc: "Build next-generation agentic workflows using Vertex AI and the Gemini model suite. Win cash prizes and direct recruitment tracks at Google Labs.",
    externalLink: "https://developers.google.com/ai",
    coverImage:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o2",
    category: "hackathons",
    title: "Microsoft Imagine Cup 2026",
    organizer: "Microsoft Corp",
    mode: "Online + Finals Redmond",
    deadline: "2026-09-01",
    prizePool: "$100,000 + Azure Credits",
    difficulty: "Advanced",
    eligibility: "Undergrad/Grad Students",
    tech: "Azure, OpenAI, C#/.NET",
    seatsLeft: 120,
    parthed_og: false,
    desc: "The premier global student technology competition. Pitch and deploy an AI-driven startup concept using Microsoft Cloud architectures.",
    externalLink: "https://imaginecup.microsoft.com",
    coverImage:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o3",
    category: "hackathons",
    title: "Kaggle Deep Learning Sprint",
    organizer: "PathEd x Kaggle Group",
    mode: "Online",
    deadline: "2026-08-20",
    prizePool: "$25,000 + GPU Instances",
    difficulty: "Intermediate",
    eligibility: "All Kaggle Registered Users",
    tech: "Keras, PyTorch, Jax",
    seatsLeft: 42,
    parthed_og: true,
    desc: "Train models to optimize edge processing latency on miniature drone microcontrollers. Compute sponsorships provided directly by PathEd OG.",
    externalLink: "https://kaggle.com",
    coverImage:
      "https://images.unsplash.com/photo-1527474305487-b87b222841cc?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o4",
    category: "hackathons",
    title: "NASA Space Apps Challenge",
    organizer: "NASA Earth Sciences",
    mode: "Hybrid",
    deadline: "2026-10-05",
    prizePool: "Global Recognition & VIP Travel",
    difficulty: "All Levels",
    eligibility: "Open to Public",
    tech: "GIS Data, Python, WebGL",
    seatsLeft: 230,
    parthed_og: false,
    desc: "Use NASA's open-source climate and planetary data to construct interactive models showing global thermal updates and oceanic flows.",
    externalLink: "https://spaceapps.nasa.org",
    coverImage:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o5",
    category: "hackathons",
    title: "Smart India Hackathon 2026",
    organizer: "Ministry of Education",
    mode: "Offline (National Centers)",
    deadline: "2026-08-30",
    prizePool: "₹1,00,000 per Problem Statement",
    difficulty: "Intermediate",
    eligibility: "College Students Only",
    tech: "React, Node.js, Blockchain, IoT",
    seatsLeft: 18,
    parthed_og: false,
    desc: "India's largest national initiative addressing real-world civic challenges in waste management, clean energy, and agricultural supplies.",
    externalLink: "https://sih.gov.in",
    coverImage:
      "https://images.unsplash.com/photo-1515378791036-0648a3ef77b2?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o6",
    category: "hackathons",
    title: "Vite Global Buildathon 2026",
    organizer: "Vite Core Team",
    mode: "Online",
    deadline: "2026-11-12",
    prizePool: "$30,000",
    difficulty: "Intermediate",
    eligibility: "Web Developers",
    tech: "Vite, Rolldown, TypeScript",
    seatsLeft: 95,
    parthed_og: false,
    desc: "Optimize web bundling speed and package loading using Vite's next-generation Rust-powered compilation pipeline tools.",
    externalLink: "https://vite.build",
    coverImage:
      "https://images.unsplash.com/photo-1618401471353-b98aedd07871?auto=format&fit=crop&q=80&w=400",
  },

  // ── Internships & placement openings ───────────────────────────────────────
  {
    id: "o7",
    category: "internships",
    title: "Meta Backend Engineering Cohort",
    organizer: "Meta Career Services x PathEd",
    mode: "Hybrid (London/Remote)",
    deadline: "2026-08-10",
    prizePool: "₹1.5 Lakhs/Month Stipend",
    difficulty: "Advanced",
    eligibility: "Final Year SDE Students",
    tech: "Rust, Hack, Distributed Systems",
    seatsLeft: 15,
    parthed_og: true,
    desc: "Natively integrated training cohort with Meta Infrastructure. Selected students work directly on caching layers for Instagram.",
    externalLink: "https://careers.meta.com",
    coverImage:
      "https://images.unsplash.com/photo-1486312338219-ce68d2c6f44d?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o8",
    category: "internships",
    title: "Google STEP Internship 2026",
    organizer: "Google University Relations",
    mode: "Onsite (Bangalore/Hyderabad)",
    deadline: "2026-08-25",
    prizePool: "Competitive Stipend + Mentors",
    difficulty: "Intermediate",
    eligibility: "2nd Year B.Tech Students",
    tech: "C++, Java, Software Testing",
    seatsLeft: 40,
    parthed_og: false,
    desc: "STEP is a developmental summer internship for students who have a passion for computer science and engineering roles.",
    externalLink: "https://careers.google.com",
    coverImage:
      "https://images.unsplash.com/photo-1498050108023-c5249f4df085?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o9",
    category: "internships",
    title: "NVIDIA CUDA Optimization Program",
    organizer: "NVIDIA Research India",
    mode: "Online",
    deadline: "2026-09-05",
    prizePool: "CUDA Certified + NVIDIA GPU Grant",
    difficulty: "Advanced",
    eligibility: "Pre-Final/Final Year B.Tech",
    tech: "C, CUDA, High-Performance GPU",
    seatsLeft: 22,
    parthed_og: true,
    desc: "Learn GPU programming directly from NVIDIA researchers. Optimize execution grids for large AI matrix multiplications.",
    externalLink: "https://nvidia.com/careers",
    coverImage:
      "https://images.unsplash.com/photo-1518770660439-4636190af475?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o10",
    category: "internships",
    title: "Amazon SDE Summer Intern",
    organizer: "Amazon Student Programs",
    mode: "Onsite (Chennai/Gurugram)",
    deadline: "2026-09-20",
    prizePool: "₹85k/Month + PPO Tracks",
    difficulty: "Intermediate",
    eligibility: "3rd Year CS Students",
    tech: "Java, AWS DynamoDB, SpringBoot",
    seatsLeft: 60,
    parthed_og: false,
    desc: "Build APIs, microservices, and client-facing interfaces deployed across Amazon retail pipelines. Mentorship by senior SDE-IIs.",
    externalLink: "https://amazon.jobs",
    coverImage:
      "https://images.unsplash.com/photo-1460925895917-afdab827c52f?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o11",
    category: "internships",
    title: "Stripe Payment Systems Lab",
    organizer: "Stripe APAC Recruitment",
    mode: "Remote",
    deadline: "2026-08-18",
    prizePool: "$4,500 Monthly Stipend",
    difficulty: "Advanced",
    eligibility: "All Tech Undergrads",
    tech: "Ruby, Go, PostgreSQL, Redis",
    seatsLeft: 8,
    parthed_og: false,
    desc: "Help design fraud prevention systems and payment routing layers targeting merchant payouts across Southeast Asia countries.",
    externalLink: "https://stripe.com/jobs",
    coverImage:
      "https://images.unsplash.com/photo-1559526324-4b87b5e36e44?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o12",
    category: "internships",
    title: "CrowdStrike Cybersec Fellowship",
    organizer: "CrowdStrike University",
    mode: "Hybrid (Pune/Remote)",
    deadline: "2026-09-15",
    prizePool: "Fellowship Stipend + PPO Opportunity",
    difficulty: "Advanced",
    eligibility: "Graduating Batch 2026",
    tech: "C, Go, Linux Kernel Architecture",
    seatsLeft: 12,
    parthed_og: false,
    desc: "Deep dive into kernel exploitation, agent instrumentation, threat telemetry parsing, and endpoint protection algorithms.",
    externalLink: "https://crowdstrike.jobs",
    coverImage:
      "https://images.unsplash.com/photo-1550751827-4bd374c3f58b?auto=format&fit=crop&q=80&w=400",
  },

  // ── Scholarships & research programs ───────────────────────────────────────
  {
    id: "o13",
    category: "scholarships",
    title: "Stanford Quantum Computing Lab Research",
    organizer: "Stanford Q-Lab x PathEd",
    mode: "Hybrid",
    deadline: "2026-10-10",
    prizePool: "Fully Funded Research Fellowship",
    difficulty: "Advanced",
    eligibility: "B.Tech/M.Tech Students",
    tech: "Qiskit, Python, Quantum Mechanics",
    seatsLeft: 5,
    parthed_og: true,
    desc: "Exclusive fellowship program researching qubit stability. Fully funded travel to Stanford for summer residency sessions.",
    externalLink: "https://quantum.stanford.edu",
    coverImage:
      "https://images.unsplash.com/photo-1635070041078-e363dbe005cb?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o14",
    category: "scholarships",
    title: "Google PhD Fellowship 2026",
    organizer: "Google Research",
    mode: "Remote / Campus Visits",
    deadline: "2026-09-30",
    prizePool: "$50,000 + Google Research Mentor",
    difficulty: "Advanced",
    eligibility: "PhD Research Candidates",
    tech: "AI Research, Data Mining, Robotics",
    seatsLeft: 15,
    parthed_og: false,
    desc: "Financial support for graduate students pursuing influential research in computer science and related fields worldwide.",
    externalLink: "https://research.google/fellows",
    coverImage:
      "https://images.unsplash.com/photo-1523240795612-9a054b0db644?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o15",
    category: "scholarships",
    title: "PathEd OG AI Research Fellow",
    organizer: "PathEd Labs Group",
    mode: "Remote",
    deadline: "2026-08-22",
    prizePool: "₹50,000 Monthly Research Grant",
    difficulty: "Advanced",
    eligibility: "All Active PathEd Users",
    tech: "PyTorch, Transformers, LLM Training",
    seatsLeft: 10,
    parthed_og: true,
    desc: "PathEd hosted AI research fellowship. Research transformer optimization schemes and publish papers under PathEd Labs sponsorship.",
    externalLink: "https://pathed.org/research",
    coverImage:
      "https://images.unsplash.com/photo-1507679799987-c73779587ccf?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o16",
    category: "scholarships",
    title: "Microsoft Research Grant",
    organizer: "MSR India",
    mode: "Remote / Bangalore Residency",
    deadline: "2026-11-01",
    prizePool: "Research Grant + Internship Track",
    difficulty: "Advanced",
    eligibility: "CS Academics & Students",
    tech: "Theoretical CS, Security, ML",
    seatsLeft: 20,
    parthed_og: false,
    desc: "Microsoft Research India grant targeting projects related to social good, system scalability, and zero-knowledge proofs.",
    externalLink: "https://microsoft.com/research",
    coverImage:
      "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o17",
    category: "scholarships",
    title: "Adobe Women in Tech Scholarship",
    organizer: "Adobe India",
    mode: "Direct Scholarship",
    deadline: "2026-09-12",
    prizePool: "Full Tuition Coverage + Adobe Intern",
    difficulty: "Intermediate",
    eligibility: "Female CS Undergrad Students",
    tech: "Software Development, Cloud Tech",
    seatsLeft: 30,
    parthed_og: false,
    desc: "Adobe's annual fellowship recognizing women leaders in computing. Receives full academic funding and SDE intern offer.",
    externalLink: "https://adobe.com/careers",
    coverImage:
      "https://images.unsplash.com/photo-1531482615713-2afd69097998?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o18",
    category: "scholarships",
    title: "Venice Summer AI School",
    organizer: "Venice Research Consortium",
    mode: "Offline (Venice, Italy)",
    deadline: "2026-07-28",
    prizePool: "Tuition Waiver & Lodging Support",
    difficulty: "Advanced",
    eligibility: "Graduate Students & Researchers",
    tech: "Causal Inference, Neural Networks",
    seatsLeft: 5,
    parthed_og: false,
    desc: "An intensive 2-week school examining causal machine learning and neural architectures in historic Venice.",
    externalLink: "https://veniceai.eu",
    coverImage:
      "https://images.unsplash.com/photo-1544717305-2782549b5136?auto=format&fit=crop&q=80&w=400",
  },

  // ── Bootcamps & cohorts ────────────────────────────────────────────────────
  {
    id: "o19",
    category: "bootcamps",
    title: "PathEd Full Stack Launchpad",
    organizer: "PathEd Elite Academics",
    mode: "Online (Daily Cohorts)",
    deadline: "2026-08-01",
    prizePool: "Project Certification + Hiring Guarantee",
    difficulty: "Intermediate",
    eligibility: "All PathEd Registered Users",
    tech: "Next.js, Tailwind, Postgres, Docker",
    seatsLeft: 150,
    parthed_og: true,
    desc: "Build 3 production-ready enterprise SaaS products. Fully synchronized mentoring and placement reviews included.",
    externalLink: "https://pathed.org/bootcamp",
    coverImage:
      "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o20",
    category: "bootcamps",
    title: "Y Combinator Startup School",
    organizer: "Y Combinator",
    mode: "Online",
    deadline: "2026-09-15",
    prizePool: "Direct Pitch Access to YC Partners",
    difficulty: "All Levels",
    eligibility: "Aspiring Founders",
    tech: "MVP Construction, Startup Tech Stack",
    seatsLeft: 500,
    parthed_og: false,
    desc: "A free 6-week online course on how to start a startup, featuring talks from YC founders, developers, and investors.",
    externalLink: "https://startupschool.org",
    coverImage:
      "https://images.unsplash.com/photo-1556761175-b413da4baf72?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o21",
    category: "bootcamps",
    title: "PathEd Systems Architect Bootcamp",
    organizer: "PathEd Infrastructure Group",
    mode: "Online",
    deadline: "2026-08-28",
    prizePool: "Systems Mastery Badge + Server Credits",
    difficulty: "Advanced",
    eligibility: "CRI Score > 80%",
    tech: "Distributed Databases, Kubernetes, Kafka",
    seatsLeft: 60,
    parthed_og: true,
    desc: "Deep-dive cohort exploring multi-region database replication, stream processing bottlenecks, and high availability systems.",
    externalLink: "https://pathed.org/system",
    coverImage:
      "https://images.unsplash.com/photo-1517694712202-14dd9538aa97?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o22",
    category: "bootcamps",
    title: "A16z Crypto Startup School",
    organizer: "a16z crypto LLC",
    mode: "Offline Residency (LA)",
    deadline: "2026-10-15",
    prizePool: "$500,000 Seed Investment Guarantee",
    difficulty: "Advanced",
    eligibility: "Web3/Blockchain Developers",
    tech: "Solidity, Rust, Zero Knowledge Proofs",
    seatsLeft: 25,
    parthed_og: false,
    desc: "Accelerated program designed for web3 developers building decentralized products. Mentoring by world-class web3 engineers.",
    externalLink: "https://a16z.com",
    coverImage:
      "https://images.unsplash.com/photo-1621761191319-c6fb62004040?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o23",
    category: "bootcamps",
    title: "Supabase Serverless Bootcamp",
    organizer: "Supabase Team",
    mode: "Online",
    deadline: "2026-09-08",
    prizePool: "Premium Swag Box + Supabase Pro",
    difficulty: "Intermediate",
    eligibility: "Web Developers",
    tech: "PostgreSQL, Supabase, Row Level Security",
    seatsLeft: 300,
    parthed_og: false,
    desc: "Master serverless database structures, real-time channels, file storage buckets, and postgres function hooks in 2 weeks.",
    externalLink: "https://supabase.com/school",
    coverImage:
      "https://images.unsplash.com/photo-1542744094-3a31f103e35f?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o24",
    category: "bootcamps",
    title: "Redis Distributed Caching School",
    organizer: "Redis Labs",
    mode: "Online",
    deadline: "2026-08-19",
    prizePool: "Certified Redis Developer Exam Pass",
    difficulty: "Intermediate",
    eligibility: "Back-end Developers",
    tech: "Redis, Node.js, Spring Boot",
    seatsLeft: 180,
    parthed_og: false,
    desc: "Understand cache eviction schemes, pub/sub models, geohashes, and Redis modules (Search, JSON, TimeSeries) for latency improvements.",
    externalLink: "https://redis.com",
    coverImage:
      "https://images.unsplash.com/photo-1558494949-ef010cbdcc31?auto=format&fit=crop&q=80&w=400",
  },

  // ── Workshops & technical seminars ─────────────────────────────────────────
  {
    id: "o25",
    category: "workshops",
    title: "High Performance Kafka Workshops",
    organizer: "PathEd Labs x Confluent",
    mode: "Online",
    deadline: "2026-08-08",
    prizePool: "Confluent Certificate Voucher",
    difficulty: "Advanced",
    eligibility: "Back-end Developers",
    tech: "Apache Kafka, Zookeeper, Java",
    seatsLeft: 30,
    parthed_og: true,
    desc: "Fine-tune partition counts, message queue configurations, lag offsets, and consumer groups for high-throughput pipelines.",
    externalLink: "https://confluent.io",
    coverImage:
      "https://images.unsplash.com/photo-1540575467063-178a50c2df87?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o26",
    category: "workshops",
    title: "AWS Distributed Microservices Seminar",
    organizer: "Amazon Web Services",
    mode: "Online",
    deadline: "2026-08-30",
    prizePool: "$100 AWS Sandbox Credits",
    difficulty: "Intermediate",
    eligibility: "Cloud Beginners & Intermediates",
    tech: "AWS Lambda, ECS, API Gateway",
    seatsLeft: 500,
    parthed_og: false,
    desc: "Learn to deploy scalable APIs, orchestrate containers, and log request parameters using CloudWatch metrics.",
    externalLink: "https://aws.amazon.com",
    coverImage:
      "https://images.unsplash.com/photo-1454165804606-c3d57bc86b40?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o27",
    category: "workshops",
    title: "PathEd Low Level System Design",
    organizer: "PathEd OG Instructors",
    mode: "Online (Interactive Live)",
    deadline: "2026-08-25",
    prizePool: "LLD Professional Credentials",
    difficulty: "Intermediate",
    eligibility: "Pre-Final/Final Year CS",
    tech: "Java, OOP, Design Patterns",
    seatsLeft: 45,
    parthed_og: true,
    desc: "Learn LLD by building real-world software components (Parking Lot, Movie Ticket Booking, Chess Engine) in real-time code classes.",
    externalLink: "https://pathed.org/lld",
    coverImage:
      "https://images.unsplash.com/photo-1531535934200-8734a5a2c65b?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o28",
    category: "workshops",
    title: "Docker Containerization Lab",
    organizer: "Docker Inc",
    mode: "Online Self-Paced",
    deadline: "2026-09-18",
    prizePool: "Docker Certified Associate voucher",
    difficulty: "Intermediate",
    eligibility: "Open to All",
    tech: "Docker, Docker Compose, Linux CMD",
    seatsLeft: 400,
    parthed_og: false,
    desc: "Containerize multi-container web apps, build docker configurations, and manage docker networks for microservices architectures.",
    externalLink: "https://docker.com",
    coverImage:
      "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o29",
    category: "workshops",
    title: "React Server Components Mastery",
    organizer: "Vercel Dev Relations",
    mode: "Online",
    deadline: "2026-09-29",
    prizePool: "Next.js certification discount",
    difficulty: "Intermediate",
    eligibility: "Frontend Developers",
    tech: "Next.js App Router, React 19",
    seatsLeft: 220,
    parthed_og: false,
    desc: "Master RSCs, server actions, optimistic UI updates, hydration, and streaming UI with Suspense boundaries.",
    externalLink: "https://vercel.com",
    coverImage:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o30",
    category: "workshops",
    title: "OpenAPI Swagger Design Seminar",
    organizer: "SmartBear Software",
    mode: "Online",
    deadline: "2026-08-11",
    prizePool: "SmartBear API Cert Exam",
    difficulty: "All Levels",
    eligibility: "API Developers",
    tech: "OpenAPI 3.1, Swagger, Postman",
    seatsLeft: 120,
    parthed_og: false,
    desc: "Write detailed API descriptions, generate client SDKs, and build mock servers directly from swagger configuration files.",
    externalLink: "https://swagger.io",
    coverImage:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400",
  },

  // ── Tech conferences & summits ─────────────────────────────────────────────
  {
    id: "o31",
    category: "conferences",
    title: "PathEd Global AI Summit 2026",
    organizer: "PathEd Labs Global",
    mode: "Offline (New Delhi)",
    deadline: "2026-08-20",
    prizePool: "₹5 Lakhs Startup Pitch Grant",
    difficulty: "All Levels",
    eligibility: "All PathEd Premium Users",
    tech: "Generative AI, Large Language Models",
    seatsLeft: 15,
    parthed_og: true,
    desc: "PathEd's annual technical summit. Connect with AI engineers, tech founders, VC funding networks, and research labs.",
    externalLink: "https://pathed.org/summit",
    coverImage:
      "https://images.unsplash.com/photo-1505373877841-8d25f7d46678?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o32",
    category: "conferences",
    title: "Google I/O 2026 Extended",
    organizer: "GDG Bangalore",
    mode: "Offline (Bangalore)",
    deadline: "2026-08-27",
    prizePool: "GDG Swag + Networking dinner",
    difficulty: "All Levels",
    eligibility: "Open via Lottery System",
    tech: "Gemini Nano, Android 17, WebGPU",
    seatsLeft: 150,
    parthed_og: false,
    desc: "Local community-led developer conference covering Google's latest releases in AI, mobile, web, and cloud computing frameworks.",
    externalLink: "https://io.google",
    coverImage:
      "https://images.unsplash.com/photo-1511578314322-379afb476865?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o33",
    category: "conferences",
    title: "PathEd Developer Synergy Summit",
    organizer: "PathEd Synergy Group",
    mode: "Hybrid (Pune / Online)",
    deadline: "2026-09-08",
    prizePool: "Synergy Hackathon Invitation",
    difficulty: "All Levels",
    eligibility: "Open to All Registered Users",
    tech: "System Architectures, NextGen Web",
    seatsLeft: 80,
    parthed_og: true,
    desc: "Annual synergy gathering for software teams. Share developer workflows, Git automation configurations, and build architectures.",
    externalLink: "https://pathed.org/synergy",
    coverImage:
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o34",
    category: "conferences",
    title: "Microsoft Build 2026 Extended",
    organizer: "Microsoft India",
    mode: "Offline (Hyderabad)",
    deadline: "2026-09-12",
    prizePool: "Azure Exam Vouchers",
    difficulty: "All Levels",
    eligibility: "Lottery Selection",
    tech: "Azure OpenAI, Copilot Studio, Rust",
    seatsLeft: 180,
    parthed_og: false,
    desc: "Connect with Microsoft product builders. Explore low-code development, serverless scaling, and code automation setups.",
    externalLink: "https://build.microsoft.com",
    coverImage:
      "https://images.unsplash.com/photo-1591115411646-657acc163242?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o35",
    category: "conferences",
    title: "Apple WWDC 2026 Swift Meetup",
    organizer: "Swift Developers India",
    mode: "Offline (Bangalore)",
    deadline: "2026-08-16",
    prizePool: "Apple Developer Academy Invite",
    difficulty: "All Levels",
    eligibility: "Apple Developers",
    tech: "SwiftUI, Swift 6, CoreML",
    seatsLeft: 90,
    parthed_og: false,
    desc: "WWDC wrap-up and networking meetup. Deep dive into CoreML, Swift Concurrency, and spatial app optimizations.",
    externalLink: "https://developer.apple.com",
    coverImage:
      "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "o36",
    category: "conferences",
    title: "KubeCon + CloudNativeCon",
    organizer: "Cloud Native Computing Foundation",
    mode: "Offline (New Delhi)",
    deadline: "2026-10-20",
    prizePool: "CNCF Student Travel Scholarships",
    difficulty: "Advanced",
    eligibility: "Undergrad & Grad Candidates",
    tech: "Kubernetes, Prometheus, Helm, Envoy",
    seatsLeft: 250,
    parthed_og: false,
    desc: "The cloud-native event gatherers. Connect with leading developers in Kubernetes infrastructure, observability tools, and service meshes.",
    externalLink: "https://events.linuxfoundation.org",
    coverImage:
      "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&q=80&w=400",
  },
];

export const EVENT_CATEGORIES: readonly OpportunityCategoryMeta[] = [
  {
    id: "hackathons",
    label: "Hackathons & Competitions",
    shortLabel: "Hackathons",
    description: "Showcase skills in time-limited programming challenges.",
  },
  {
    id: "internships",
    label: "Internships & Placements",
    shortLabel: "Internships",
    description: "Secure placement slots at Tier-1 technology firms.",
  },
  {
    id: "scholarships",
    label: "Scholarships & Research",
    shortLabel: "Scholarships",
    description: "Gain tuition funding and research fellowship placements.",
  },
  {
    id: "bootcamps",
    label: "Bootcamps & Cohorts",
    shortLabel: "Bootcamps",
    description: "Accelerated developmental cohorts and technology schools.",
  },
  {
    id: "workshops",
    label: "Workshops & Seminars",
    shortLabel: "Workshops",
    description: "Interactive technical training sessions and API designs.",
  },
  {
    id: "conferences",
    label: "Tech Conferences & Summits",
    shortLabel: "Conferences",
    description: "Synergy gatherings and tech startup pitching venues.",
  },
];
