import type {
  Opportunity,
  OpportunityCategoryMeta,
} from "@/components/opportunities/types";

/**
 * PathEd OG catalogue — first-party tracks, every entry `parthed_og`.
 *
 * Unlike the events catalogue these all carry a `tier`: `premium` entries are
 * filtered out of the list for free-plan students (see `PlatformOgOpportunities`),
 * which is why the locked count is surfaced honestly rather than silently.
 */
export const OG_OPPORTUNITIES: readonly Opportunity[] = [
  // ── Hackathons ─────────────────────────────────────────────────────────────
  {
    id: "og_h1",
    category: "hackathons",
    title: "PathEd Elite Code Challenge 2026",
    organizer: "PathEd Labs",
    mode: "Online",
    deadline: "2026-08-30",
    prizePool: "₹1,50,000 + SDE Interview Bypass",
    difficulty: "Advanced",
    eligibility: "UG Engineering Students",
    tech: "DSA, Algorithms, performance optimization",
    seatsLeft: 45,
    parthed_og: true,
    tier: "free",
    desc: "Our flagship monthly algorithms challenge. Solve 5 advanced optimization problems in C++ or Java within 3 hours. Top performers bypass screening at Stripe and Google.",
    externalLink: "https://pathed.org/challenge",
    coverImage:
      "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_h2",
    category: "hackathons",
    title: "Vanguard Web3 Global Hackathon",
    organizer: "Solana Foundation x PathEd",
    mode: "Online",
    deadline: "2026-09-10",
    prizePool: "$50,000 in Grants + Developer Badges",
    difficulty: "Intermediate",
    eligibility: "Open to All Developers",
    tech: "Rust, Solana Web3, React",
    seatsLeft: 80,
    parthed_og: true,
    tier: "free",
    desc: "Build decentralized finance or social protocol prototypes using Solana edge clusters. Includes 1-on-1 architecture reviews with PathEd mentors.",
    externalLink: "https://solana.com",
    coverImage:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_h3",
    category: "hackathons",
    title: "OpenAI Agentic Swarm Hackathon",
    organizer: "OpenAI x PathEd Premium",
    mode: "Online + Finals San Francisco",
    deadline: "2026-09-25",
    prizePool: "$100,000 + API Credits + SDE Referrals",
    difficulty: "Advanced",
    eligibility: "Premium Registered Members",
    tech: "GPT Agents, Python, LangChain",
    seatsLeft: 12,
    parthed_og: true,
    tier: "premium",
    desc: "Premium Exclusive. Prototype multi-agent swarms designed to coordinate code generation and automatic debugging workflows. Direct recruiting track at OpenAI.",
    externalLink: "https://openai.com",
    coverImage:
      "https://images.unsplash.com/photo-1527474305487-b87b222841cc?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_h4",
    category: "hackathons",
    title: "Adobe Creative AI Sprint 2026",
    organizer: "Adobe India x PathEd",
    mode: "Hybrid",
    deadline: "2026-08-28",
    prizePool: "₹10,00,000 + Creative Cloud Passes",
    difficulty: "Intermediate",
    eligibility: "All Premium Students",
    tech: "Generative AI, WebGL, PyTorch",
    seatsLeft: 18,
    parthed_og: true,
    tier: "premium",
    desc: "Premium Exclusive. Build canvas-based collaborative generative image editing pipelines using Adobe Firefly models. Winners get direct SDE-1 interviews.",
    externalLink: "https://adobe.com",
    coverImage:
      "https://images.unsplash.com/photo-1451187580459-43490279c0fa?auto=format&fit=crop&q=80&w=400",
  },

  // ── Bootcamps ──────────────────────────────────────────────────────────────
  {
    id: "og_b1",
    category: "bootcamps",
    title: "PathEd Full-Stack SDE Bootcamp",
    organizer: "PathEd Academy",
    mode: "Online (Cohort-based)",
    deadline: "2026-08-20",
    prizePool: "Verified Capstone Portfolio Badge",
    difficulty: "Intermediate",
    eligibility: "Open to All Registered Users",
    tech: "React, Node.js, MongoDB",
    seatsLeft: 150,
    parthed_og: true,
    tier: "free",
    desc: "Accelerated 8-week bootcamp focusing on full-stack application development. Deploy 3 web apps to cloud environments under peer sprint reviews.",
    externalLink: "https://pathed.org/bootcamp",
    coverImage:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_b2",
    category: "bootcamps",
    title: "Docker & Kubernetes DevOps Cohort",
    organizer: "DevOps India x PathEd",
    mode: "Online (Saturdays)",
    deadline: "2026-08-22",
    prizePool: "Docker Certification Voucher",
    difficulty: "All Levels",
    eligibility: "Undergrad CS Students",
    tech: "Docker, Kubernetes, GitHub Actions",
    seatsLeft: 200,
    parthed_og: true,
    tier: "free",
    desc: "Master container orchestrations, CI/CD pipeline automation, and horizontal scaling strategies on AWS cloud infrastructure.",
    externalLink: "https://docker.com",
    coverImage:
      "https://images.unsplash.com/photo-1605810230434-7631ac76ec81?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_b3",
    category: "bootcamps",
    title: "System Design & Distributed Ledgers",
    organizer: "Stripe Eng x PathEd Premium",
    mode: "Online (Closed Cohort)",
    deadline: "2026-09-05",
    prizePool: "Stripe Engineering Mentorship Pass",
    difficulty: "Advanced",
    eligibility: "Premium Registered Members",
    tech: "System Design, Redis, Kafka",
    seatsLeft: 10,
    parthed_og: true,
    tier: "premium",
    desc: "Premium Exclusive. 6-week cohort on building high-concurrency payment integrations, cache invalidations, and distributed lock patterns.",
    externalLink: "https://stripe.com",
    coverImage:
      "https://images.unsplash.com/photo-1555066931-4365d14bab8c?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_b4",
    category: "bootcamps",
    title: "Generative AI & LLM Fine-Tuning",
    organizer: "Google Labs x PathEd Premium",
    mode: "Hybrid",
    deadline: "2026-09-12",
    prizePool: "GCP AI Specialist Exam Voucher",
    difficulty: "Advanced",
    eligibility: "Premium Registered Members",
    tech: "LLMs, LoRA, PyTorch, Vertex AI",
    seatsLeft: 14,
    parthed_og: true,
    tier: "premium",
    desc: "Premium Exclusive. Hands-on intensive cohort on fine-tuning llama-based models for custom databases. Covers tokenizations and deployment.",
    externalLink: "https://google.com",
    coverImage:
      "https://images.unsplash.com/photo-1582213782179-e0d53f98f2ca?auto=format&fit=crop&q=80&w=400",
  },

  // ── Workshops & webinars ───────────────────────────────────────────────────
  {
    id: "og_w1",
    category: "workshops",
    title: "React 19 Server Actions Masterclass",
    organizer: "Vercel x PathEd",
    mode: "Online Webinar",
    deadline: "2026-08-15",
    prizePool: "React Core Sync Certification",
    difficulty: "Intermediate",
    eligibility: "Frontend Web Developers",
    tech: "Next.js 15, React Actions",
    seatsLeft: 300,
    parthed_og: true,
    tier: "free",
    desc: "Deep dive into RSCs, optimistic updates, database triggers from forms, and server-side state hydration without client hooks.",
    externalLink: "https://vercel.com",
    coverImage:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_w2",
    category: "workshops",
    title: "SQL Performance & Query Optimization",
    organizer: "Oracle Dev x PathEd",
    mode: "Online Webinar",
    deadline: "2026-08-18",
    prizePool: "PathEd Query Optimizer Badge",
    difficulty: "All Levels",
    eligibility: "Database Enthusiasts",
    tech: "SQL, DBMS Indexing, PostgreSQL",
    seatsLeft: 400,
    parthed_og: true,
    tier: "free",
    desc: "A 4-hour live webinar demonstrating transaction isolation levels, indexing mechanics, query plans, and connection pool tuning.",
    externalLink: "https://oracle.com",
    coverImage:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_w3",
    category: "workshops",
    title: "Rust Concurrency & Memory Safety",
    organizer: "Rust India x PathEd Premium",
    mode: "Online Interactive Live Lab",
    deadline: "2026-09-02",
    prizePool: "Elite Rust Developer Credential",
    difficulty: "Advanced",
    eligibility: "Premium Registered Members",
    tech: "Rust, Concurrency, Cargo",
    seatsLeft: 25,
    parthed_og: true,
    tier: "premium",
    desc: "Premium Exclusive. Live workshop covering thread spawning, message passing channels, Arc/Mutex usage, and safe memory management without garbage collection.",
    externalLink: "https://rust-lang.org",
    coverImage:
      "https://images.unsplash.com/photo-1551288049-bebda4e38f71?auto=format&fit=crop&q=80&w=400",
  },
  {
    id: "og_w4",
    category: "workshops",
    title: "System Security & Penetration Testing",
    organizer: "Shield Labs x PathEd Premium",
    mode: "Online Live Lab",
    deadline: "2026-09-18",
    prizePool: "Ethical Hacker Entry Pass",
    difficulty: "Advanced",
    eligibility: "Premium Registered Members",
    tech: "Linux, Web Security, OWASP",
    seatsLeft: 20,
    parthed_og: true,
    tier: "premium",
    desc: "Premium Exclusive. Live lab simulating common exploits like SQL injection, CSRF, and SSRF. Learn to harden APIs against unauthorized access.",
    externalLink: "https://owasp.org",
    coverImage:
      "https://images.unsplash.com/photo-1528605248644-14dd04022da1?auto=format&fit=crop&q=80&w=400",
  },
];

export const OG_CATEGORIES: readonly OpportunityCategoryMeta[] = [
  {
    id: "hackathons",
    label: "Hackathons & Competitions",
    shortLabel: "Hackathons",
    description: "Showcase skills in time-limited programming challenges.",
  },
  {
    id: "bootcamps",
    label: "Bootcamps & Cohorts",
    shortLabel: "Bootcamps",
    description: "Accelerated developmental cohorts and technology schools.",
  },
  {
    id: "workshops",
    label: "Workshops & Webinars",
    shortLabel: "Workshops",
    description: "Interactive technical training sessions and API designs.",
  },
];
