import { RoadmapNode, RoadmapEdge, RoadmapProfile } from '@/types/roadmap';
import { callGemini } from './gemini';
import { roadmapSchema } from '@/lib/validation/roadmap-schemas';
import { AppError } from '@/lib/api/errors';

/** Keep the profile payload small — DB rows include ids/timestamps the model does not need. */
function compactProfile(profile: RoadmapProfile) {
  return {
    currentStudy: profile.currentStudy,
    yearSemester: profile.yearSemester,
    academicBackground: profile.academicBackground,
    enjoyedSubjects: profile.enjoyedSubjects,
    struggledSubjects: profile.struggledSubjects,
    careerGoal: profile.careerGoal,
    targetRole: profile.targetRole,
    knownSkills: profile.knownSkills,
    hasProjects: profile.hasProjects,
    projects: profile.projects?.slice(0, 5),
    experienceLevel: profile.experienceLevel,
    wantToLearn: profile.wantToLearn,
    learningMotivation: profile.learningMotivation,
    weeklyHours: profile.weeklyHours,
    projectVsLearning: profile.projectVsLearning,
    learningStyles: profile.learningStyles,
    targetTimeline: profile.targetTimeline,
    topPriority: profile.topPriority,
    aiFollowUpAnswers: profile.aiFollowUpAnswers,
  };
}

export async function generateRoadmap(profile: RoadmapProfile, userId: string): Promise<{ title: string; targetRole: string; estimatedWeeks: number; nodes: RoadmapNode[]; edges: RoadmapEdge[] }> {
  const systemInstruction = `You are an expert career coach and learning path architect.
Create a PERSONALIZED learning roadmap as a directed acyclic graph (DAG).

Hard limits (must obey — oversized JSON will be truncated):
- Generate 12-18 nodes total (not more).
- 1 goal, 2-3 milestones, 2-3 phases; remaining nodes are skills/projects/checkpoints.
- description: max 1 short sentence (~120 chars).
- whyLearn: max 1 short sentence (~100 chars).
- resources: 0-2 per node; prefer real URLs.
- skills/topics: 1-3 short strings each.
- project field: null unless type is project (then one short sentence).
- Node IDs: unique kebab-case.
- status: always "locked".
- Edges: one edge per dependency; source = prerequisite, target = dependent.
- Skip topics the student already knows at advanced/very_confident.
- Scale estimatedHours to weeklyHours and targetTimeline.

Return ONLY valid JSON matching:
{
  "title": "string",
  "targetRole": "string",
  "estimatedWeeks": number,
  "nodes": [{
    "id": "string",
    "type": "goal|milestone|phase|skill|topic|project|resource|checkpoint|career",
    "title": "string",
    "description": "string",
    "status": "locked",
    "priority": "low|medium|high|critical",
    "estimatedHours": number,
    "dependencies": ["node-id"],
    "skills": ["string"],
    "topics": ["string"],
    "resources": [{"title":"string","url":"string","type":"documentation|video|course|practice|article|project"}],
    "project": "string|null",
    "whyLearn": "string"
  }],
  "edges": [{"id":"string","source":"string","target":"string","label":"string"}]
}`;

  const prompt = `Generate a personalized roadmap for this student profile:\n${JSON.stringify(compactProfile(profile))}`;

  try {
    const result = await callGemini<any>({
      prompt,
      systemInstruction,
      userId,
      timeoutMs: 90000,
      // Roadmap JSON is large; free-tier keys still allow high output caps on 2.5 Flash.
      maxOutputTokens: 65536,
    });

    const validatedResult = roadmapSchema.parse(result);
    return validatedResult as { title: string; targetRole: string; estimatedWeeks: number; nodes: RoadmapNode[]; edges: RoadmapEdge[] };
  } catch (error) {
    if (error && typeof error === 'object' && 'name' in error && error.name === 'ZodError') {
      console.error("Zod Validation Failed:", JSON.stringify((error as any).errors, null, 2));
      throw AppError.badRequest('Invalid roadmap generated by AI. Please try again.');
    }
    throw error;
  }
}
