import { RoadmapProfile, FollowUpQuestionsResponse } from '@/types/roadmap';
import { callAIWithFallback } from './llm';
import { followUpQuestionsResponseSchema } from '@/lib/validation/roadmap-schemas';
import { AppError } from '@/lib/api/errors';

export async function generateFollowUpQuestions(profile: RoadmapProfile, userId: string): Promise<FollowUpQuestionsResponse> {
  const systemInstruction = `You are analyzing a student's profile to identify MISSING information needed for roadmap generation.
Generate 3-7 highly relevant follow-up questions. Each question should fill a specific knowledge gap. Do NOT ask about things already covered.
Example: If student wants AI/ML but hasn't mentioned math → ask about math comfort.
Example: If student wants cybersecurity but no mention of Linux → ask about Linux experience.
If targetCompany is already set, do NOT ask which company they want.
If they want a job, internship, or placements and targetCompany is empty, you MAY ask whether they have a target company (optional, not required).
If the profile is comprehensive enough, return { "needsMoreInformation": false, "questions": [] }.
Question types: single_choice, multi_choice, text, rating.
Each question must have an 'id' (kebab-case), 'reason' (why asking), 'required' boolean.
You MUST return valid JSON exactly matching this structure:
{
  "needsMoreInformation": boolean,
  "questions": [
    {
      "id": "string",
      "question": "string",
      "type": "single_choice|multi_choice|text|rating",
      "options": ["string"],
      "reason": "string",
      "required": boolean
    }
  ]
}`;

  const prompt = `Please analyze the following student profile and generate follow-up questions if needed:\n\n${JSON.stringify(profile, null, 2)}`;

  try {
    const result = await callAIWithFallback<any>({
      prompt,
      systemInstruction,
      userId,
      maxTokens: 4096,
      temperature: 1,
      reasoningEffort: 'medium',
    });

    const validatedResult = followUpQuestionsResponseSchema.parse(result);
    return validatedResult as FollowUpQuestionsResponse;
  } catch (error) {
    if (error && typeof error === 'object' && 'name' in error && error.name === 'ZodError') {
      console.error("Zod Validation Failed:", JSON.stringify((error as any).errors, null, 2));
      throw AppError.badRequest('Invalid follow-up questions generated by AI.');
    }
    throw error;
  }
}
